rdkmaster/jigsaw

src/app/demo/slider/basic/app.component.html, src/app/demo/slider/basic/app.component.scss, src/app/demo/slider/basic/app.component.ts, src/app/demo/slider/vertical/app.component.html, src/app/demo/slider/vertical/app.component.ts, src/jigsaw/component/slider/handle.html, src/jigsaw/component/slider/slider.html, src/jigsaw/component/slider/slider.scss, src/jigsaw/component/slider/slider.ts
fixes #280 
fixes #283
1. 修改slider在form里面绑定`ngModel`，无法正确显示初始样式
2.优化slider的布局，设置宽高
3.去掉slider多余的绑定事件
4.优化slider的设置value
5.优化slider的demo
=> Optimize slider component

src/jigsaw/component/list-and-tile/group-common.ts
=> [修复] 修复group items为空时，在destroy中会报错的问题

src/jigsaw/component/table/table-typings.ts
Change-Id: Ie84e80a3c80291a944e8e27b586d2c37f1b68782
=> [修复] 修复table不设置trackItemBy时，数据的最后字段相等会导致checkbox选择错误

src/jigsaw/component/tabs/tab.ts
=> [修复] 修复最新tab在editable-box里面会报错，fixes #870

src/app/demo/table/checkbox-column/demo.component.ts, src/jigsaw/component/table/table.ts
=> [故障] 修复table的checkbox渲染器设置初始data会导致功能不可用，fixes #925

src/jigsaw/pc-components/input/auto-complete-input.ts, src/jigsaw/pc-components/input/input.ts
这边发现了ng9的一个破坏性，就是一个组件被另一个组件继承，他的元数据即@Component也会被继承，这里的autoCompleteInput就是继承了JigsawInput的host绑定导致样式问题
autoCompleteInput本来就不应该继承JigsawInput，因为他内部有一个JigsawInput，我写一个JigsawInputBase来收集他们的公共属性
=> [故障] 修复由于ng9组件继承元数据导致autoCompleteInput样式出现问题

src/jigsaw/pc-components/date-and-time/date-time-picker.ts
=> [故障] 修复没有初始值gr为分钟或小时，选了日期后value值依旧为00:00:00

src/jigsaw/pc-components/menu/navigation-menu.ts
=> [故障] 修复导航菜单在设置showToggleButton=false和collapsed=true时的宽度问题，解决了@1250

src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I048e7e9a9acf76f0592595715ac969e1f62790bb
原本渲染器内的title功能会干扰Awade中通用的title配置，故去除。
=> 表格拖拽单元格渲染器问题修复

src/jigsaw/pc-components/list-and-tile/tile.scss
Change-Id: I060926188e7a79b0076be7c3e3b00270164828cd
=> [修复] ButtonBar组件长文本可正常显示省略号；左右两侧留白依照规范改为16px；

src/jigsaw/pc-components/date-and-time/date-picker.scss
=> [修复] range-time当前日期的右侧日期框可正常显示

src/jigsaw/pc-components/table/table.scss
Change-Id: Idbf79f910ea59537144e50bb1389850a597198a8
=> [修复] 表格列头用图标时，图标与文本对垂直居中

src/app/demo/pc/breadcrumb/demo-set.module.ts, src/app/demo/pc/breadcrumb/fold/demo.component.ts, src/app/demo/pc/breadcrumb/mode/demo.component.html, src/app/demo/pc/breadcrumb/mode/demo.component.scss, src/app/demo/pc/breadcrumb/mode/demo.component.ts, src/app/demo/pc/breadcrumb/mode/demo.module.ts, src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss, src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss, src/jigsaw/pc-components/breadcrumb/breadcrumb.scss, src/jigsaw/pc-components/header/header.scss
Change-Id: I089ba4b580e61902a58cf93e27cecb8f1135d056
https://gitlab.zte.com.cn/10045812/ng-eval/issues/2527
=> [优化] Breadcrumb组件文字底端对齐；各主题下字体颜色与规范对齐；

src/jigsaw/pc-components/menu/menu.scss
Change-Id: I6f370c15706791881bb2dba42fe7294c24560487
https://gitlab.zte.com.cn/10045812/ng-eval/issues/2555
=> [修复] Menu组件dark模式下disabled字体颜色变灰

src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: Ided47bbb746063a8d414fc44e243ad15c87b8bb0
=> [修复] 解决导航菜单在折叠起来的时候，图标没有水平居中的问题，解决了@7274

src/jigsaw/pc-components/notification/notification.scss
Change-Id: Ied34a628588909d674d24829d7073f0a408f2550
=> [修复] 解决标题或者内容比较长时，会跟关闭按钮有重叠，解决了@7273

src/jigsaw/pc-components/date-and-time/time-picker.ts
Change-Id: Ief646c7ca43f80659722fe26d70e222f9af48914
=> [故障] time组件弹出选择时分秒使用上下键盘加减时间的位置不对，解决了@7309

src/jigsaw/pc-components/transfer/transfer.ts
Change-Id: Ib591e68fca1f08d75b4eb07116e1540576519c72
=> [故障] 修复穿梭框右边列表第一次搜索不会及时更新列表，解决了@7325

src/jigsaw/pc-components/pagination/pagination.scss
Change-Id: Icc6f1d3ff8c375a75978591a22788e954695d63f
=> [修复] 解决pagination下拉框文字垂直布局中问题，解决了@7317，@7245

src/app/demo/pc/select/size/demo.component.html, src/jigsaw/pc-components/select/select.scss, src/jigsaw/pc-components/select/select.ts
Change-Id: I684ce389e8a0d3dc6ea5de9eea69e2d31c0ba2b5
=> [故障] 修复下拉多选设置宽度时选项文本太长被截掉，解决了@7218

src/jigsaw/common/directive/tooltip/tooltip.scss
Change-Id: I30d309230facc01d5cc8b2903709796de0c2ee30
=> [优化] 优化了tooltip文字过长时会超出的问题，解决了@7184

src/jigsaw/pc-components/list-and-tile/list-option.scss
Change-Id: I69a04c75089202bcec45d402739aeb5ecc0a36d7
=> [修复] 解决list-lite 组件文本垂直不居中的问题，解决了@7199

src/jigsaw/pc-components/menu/navigation-menu.html
Change-Id: If2337366b7d2767223dc477f6a4b9b73e9a2a0aa
=> [优化] 导航菜单折叠时，图标的tooltip出现在右侧，解决了@7034

src/jigsaw/pc-components/tree/tree.scss, src/jigsaw/pc-components/tree/ztree-types.ts
Change-Id: I7f91418cd884e7c86d166b22ab5af83a5cfd52bb
=> [故障] 修复树组件设置showIcon为false时依旧能显示图标，并且图标是歪的，解决了@7037

src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I2389110db02f4e9410de528f1c7feeb84f8d8ad2
=> [修复] 修复导航菜单在没有子菜单的时候，会显示一个横线，解决了@7038

src/jigsaw/common/directive/badge/badge.ts, src/jigsaw/pc-components/slider/slider.ts
Change-Id: I3b4416b258475a46ed79c2e10cde122a35b1744f
=> [故障] 修复徽章用字符串数字设置偏移会导致计算错误，解决了@7100

src/jigsaw/pc-components/dialog/dialog.scss
Change-Id: I6d8bd76a59ddea143873465b628dfbe727b5daf8
=> [优化] 增加dialog标题图标与文字间距，解决了@7203

src/jigsaw/pc-components/button/button.scss
Change-Id: Ia871fe9f6ca4d84250ac9d7824e6cb1f37a36602
=> [优化] tooltip/moving-tooltip 拖动时有动画干扰，导致tooltip位置错误，解决了@7029

src/jigsaw/common/directive/tooltip/tooltip.scss
Change-Id: I06d23a797c5be830f2f6144cfe42b2327599fc43
=> [修复] tooltip在黑暗模式下对齐颜色规范，解决了@6992

src/jigsaw/pc-components/tree/tree-ext.ts, src/jigsaw/pc-components/tree/tree.scss
Change-Id: I6d727219edcef14c3f8444e8e88aeae528d5922f
=> [修复] 解决了Tree组件在数据更新时图标不更新的问题、解决了树字体颜色不变红的问题，解决了@6980，@6990

src/jigsaw/pc-components/steps/step.scss
=> [优化] 步骤条的节点名称在较短时，右侧别截掉一点点的问题，解决了@6965

src/app/demo/pc/button-bar/size/demo.component.html, src/app/demo/pc/button-bar/size/demo.component.ts, src/jigsaw/pc-components/list-and-tile/button-bar.scss
Change-Id: I02e47f0cd1811f0491b3970837ff61e116a22489
=> [优化] 优化button-bar组件文字使用英文时底部会被切掉的问题，解决了@6900

src/jigsaw/pc-components/cascade/cascade.ts, src/ngx-formly/jigsaw/cascade/src/cascade.type.ts
原来的data属性是配置在后面的，导致配置dataGenerator被data属性的setter方法中的逻辑给覆盖了。所以要将data的配置挪到前面：
=> [故障]表单中的级联组件配置dataGenerator无效的问题

src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss, src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss, src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss, src/jigsaw/pc-components/notification/notification.scss
Change-Id: I85b327e6e4c59ffecaea710000104e651ed9ea36
本质上notification组件背景色透明，使用的是popup的背景色，且不存在透明背景的场景，故修改notification的背景色，以保两种皮肤切换时背景色可变。
=> [优化] 浅色下弹出notification，然后切换为深色，组件背景可以随之改变，解决了@6978

src/app/demo/pc/table/auto-fill-up/demo.component.html, src/app/demo/pc/table/auto-fill-up/demo.component.ts, src/app/demo/pc/table/auto-fill-up/demo.module.ts, src/jigsaw/pc-components/table/table.html, src/jigsaw/pc-components/table/table.ts
- ‘--’单元格文字左右对齐方式不好添加配置，因为每列的需求可能不一样。可以在以后table的columDefine支持配置单元格文字左右后自动读取；
=> [修复] 修复分页数据自动填充空白行过多问题；新增自动填充空白行开关；解决了@6913，@6891

src/jigsaw/pc-components/collapse/collapse.scss, src/jigsaw/pc-components/select/select.scss
Change-Id: I5318915760dafa4b3773ba14326a1ad548e8cad0
=> [优化] collapse折叠组标题栏悬浮背景变蓝；折叠下拉组件折叠组标题悬浮背景变蓝，文字变蓝；解决了@6876

src/jigsaw/pc-components/switch/switch.scss
Change-Id: I2e716cd639afe2fcd328293a705d84d4ae25e2d9
=> [优化] Switch组件对齐规范，对齐各size组件高度，解决了@6886

src/jigsaw/pc-components/button/button.ts
Change-Id: Ia58b5e2b37b73d02879c24289113d89cd4b59abc
=> [修复] 修复了button组件在弹框中宽度不对的问题，解决了@6815

src/jigsaw/pc-components/pagination/pagination.scss
Change-Id: Ia0549c6196ec724fd14e582915c71cabd46a9a62
=> [优化] 英文状态下，表格的分页按钮中的单词Page显示完全，解决了@6768

src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: Ibdbf1ef306f5d91d56c5db8e5b7786087d5e7ece
=> [优化] 树表的树节点列改为左对齐，解决了@6836

src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I94ec50d2369111adbcba4e1b3d784aca5a007ec7
=> [优化] Vmax的导航菜单一级菜单选中文本调整为白色，关联@6671

src/jigsaw/pc-components/checkbox/checkbox.scss
Change-Id: I9b68963ebe7a0ef22b4e15456822514cc476c7c9
=> [优化] checkbox的框和文本间距留白改为8px，解决了@6694

src/jigsaw/pc-components/breadcrumb/breadcrumb.scss
Change-Id: I3e8be68594c3cfb641dc5dd040847d645d64a55f
=> [优化] Breadcrumb组件当前页文字取消悬浮下划线，解决了@6726

src/jigsaw/pc-components/tree/tree-ext.ts, src/jigsaw/pc-components/tree/tree.scss
Change-Id: Iaea5efcf70746e539ec0e7f3cb9685078e5cf7e3
=> [优化] Jigsaw-tree修改节点、删除节点图标更新；图标大小对齐规范；解决了@6723

src/jigsaw/pc-components/switch/switch.scss
Change-Id: I96744e07f942500a310ee541df62e2a1b387d343
=> [优化] Jigsaw-switch组件圆点阴影更显眼，解决了@6722

src/jigsaw/pc-components/tree/tree.scss
Change-Id: Ib96f29adae4374da1cc712b157a22f9e14332d0c
=> [优化]  tree组件操作按钮离文字16px距离，关联@6575

src/jigsaw/pc-components/breadcrumb/breadcrumb.scss
Change-Id: I6cc16f8b1d4057294f69cab896db75b8d9cf1050
=> [优化] Breadcrumb组件高度对齐到规范的48px，关联@6602

src/jigsaw/pc-components/transfer/transfer.ts
Change-Id: I8973196dd98c058f795c0358cbaace8e0dc4c334
=> [故障] 修复穿梭框使用普通数组作为data时无法显示数据，关联@6433

src/jigsaw/pc-components/pagination/pagination-item.scss
=> [优化] 解决了pagination组件折叠状态在宽度不足时会换行的问题，解决了@6402

src/jigsaw/pc-components/menu/navigation-menu.html
=> [优化] navigation组件展开按钮和规范对齐，解决了@6406

src/jigsaw/pc-components/table/table.scss
Change-Id: Ibf90cad543d536a45f183f3430efe271ca486cf4
=> [优化] 树表开闭的图标颜色修改为 #737373，关联了@6420

src/app/demo/pc/menu/navigation/demo.component.ts, src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I461249bc7dfb65302a4760842ab728e287b0cd21
=> [优化] Navigation组件对齐规范，包括图标大小、图标和文本间距、选中状态文本颜色；关联了@6304

src/app/demo/pc/select-group/edit-selected-items/demo.component.html, src/app/demo/pc/select-group/edit-selected-items/demo.component.ts, src/jigsaw/pc-components/select/select-base.ts
Change-Id: Ic0f880bc620a48a872be184852b0185f70cf8134
http://localhost:4200/#/pc/select-group/edit-selected-items
=> [故障]  解决了分组下拉框无法清空已选择的值的问题，关联@6301

src/jigsaw/pc-components/input/prefix-suffix-widget.scss
Change-Id: I5562db5b3ac605bf28ae7b099b3124da0c74d808
=> [优化] 优化input组件的prefix-suffix 文本过长时把下拉箭头挤掉的问题，关联了@6585

src/jigsaw/common/core/theming/prebuilt/settings/zjcm-reset.scss
Change-Id: I4251cd77ac7701fce71cd5c613bcaff39b89c5a7
=> [优化] zjcm皮肤的radio选中状态原点位置优化，关联了@6250

src/app/demo/pc/toast/full/demo.component.ts, src/jigsaw/pc-components/toast/toast.scss, src/jigsaw/pc-components/toast/toast.ts
Change-Id: Ia2c63a78a01f5660706dd3e50f35cc56555b2c55
=> [优化] toast组件默认宽度对齐规范至256px；解决组件圆角有误的问题；关联了@6187

src/jigsaw/pc-components/tree/tree-ext.ts
Change-Id: Ia893954c92e49d9586b8a5921d8ae79fc9c8ff93
=> [故障] 解决树节点改名后进行搜索时，未及时更新节点名导致搜索结果出错的问题，关联了@6179

src/jigsaw/pc-components/table/table.scss
Change-Id: Ic46ae7ebc001a70672cb8f454886912a6f11f51e
=> [故障] 解决linux云桌面Google浏览器89.x版本下，表格的行高和标题高度不正确的问题，关联了@6090

src/jigsaw/pc-components/breadcrumb/breadcrumb.scss
Change-Id: I3273f32fad846cb07fa4a082a0c0cddd98569255
=> [优化] Breadcrumb组件左边蓝色文字部分字号改为12px，关联了@5998

src/jigsaw/common/directive/upload/upload.directive.ts
Change-Id: I593b4150d5b679a9ce5ac9e572fe8eac96d4da09
原先的_appendFiles()会在_selectFile和upload时执行，但是在multiple为false的情况下，方法对外部有影响。固把clear方法提到upload之外。
=> [故障] 解决上传组件在单选时，无法手动上传的问题，解决了@5979

src/jigsaw/pc-components/graph/graph.ts
Change-Id: I6031406666fbb17b7486bb495c459e1a0cdef94a
=> [故障] 通用图形初始化后设置空option，图形不能切到无数据的图标，关联@5924

src/app/for-internal/demo/pc/search-input/basic/demo.component.html, src/app/for-internal/demo/pc/search-input/basic/demo.component.ts, src/jigsaw/pc-components/input/search-input.ts
Change-Id: Ie9bee329b7ff1bb4089aec732674959c567bbe0b
http://localhost:4200/#/pc/search-input/basic
=> [故障] 解决search-input在通过双绑数据置空时无效的问题，解决了@5810

src/jigsaw/pc-components/input/input.scss
=> [优化] 解决input组件设置背景色有锯齿的问题，关联了@5606

src/jigsaw/pc-components/upload/index.ts, src/jigsaw/pc-components/upload/upload-result.html
=> [故障] 解决上传组件里的“重新上传”词条未国际化的问题，解决了@5412

src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss, src/jigsaw/pc-components/date-and-time/time-picker.scss, src/jigsaw/pc-components/input/input.scss, src/jigsaw/pc-components/select/select-base.ts, src/jigsaw/pc-components/select/select.html, src/jigsaw/pc-components/upload/upload.scss
=> [优化] 输入框、下拉框对齐规范；图标颜色对齐规范；解决了@6926

angular.real.json, src/jigsaw/common/core/data/graph-data.ts, src/jigsaw/mobile-components/graph/graph.ts, src/jigsaw/pc-components/graph/graph-download.directive.ts, src/jigsaw/pc-components/graph/graph.ts
应用在使用jigsaw组件时，如果使用了图形组件，需要做这样的调整：
1. 去除代码中，对echarts库的直接import，改为declare方式，如 `declare const echarts: any`。
2. 需要在angular.json或者index.html中，引入echarts。
=> [破坏性修改] 去除组件库对echarts的依赖，关联@6186

angular.real.json, src/jigsaw/common/core/data/graph-data.ts, src/jigsaw/mobile-components/graph/graph.ts, src/jigsaw/pc-components/graph/graph-download.directive.ts, src/jigsaw/pc-components/graph/graph.ts
如果应用中未直接使用echarts，而是在使用jigsaw组件时使用了图形组件，则需要做这样的调整：
1. 去除代码中，对echarts库的直接import，改为declare方式，如 declare const echarts: any。
2. 需要在angular.json或者index.html中，引入echarts。
=> [破坏性修改] 去除组件库对echarts的直接依赖，关联@6186

src/app/for-internal/demo/pc/transfer/transfer-tree/demo.component.css, src/app/for-internal/demo/pc/transfer/transfer-tree/demo.component.html, src/app/for-internal/demo/pc/transfer/transfer-tree/demo.component.ts, src/jigsaw/pc-components/transfer/renderer/transfer-renderer.ts
http://localhost:4200/#/pc/transfer/transfer-tree
=> [故障] 解决了树穿梭框，树节点依旧可以编辑的问题，解决了@5161

src/jigsaw/pc-components/menu/menu.html, src/jigsaw/pc-components/menu/menu.ts
=> [新增] 级联菜单组件在文本超出时显示tooltip，关联了@5181

src/jigsaw/common/core/data/modeled-graph-data.ts
在awade中配置直角坐标系的公共系列的这三个参数，能够影响未设置参数的维度
=> [优化] 解决直角系可视化组件配置公共系列不生效的问题，解决了@5183

src/jigsaw/mobile-components/tabs/tab.scss, src/jigsaw/pc-components/tabs/tab.scss
=> [故障] 解决tabs组件在页签较多出现下拉列表时，挡住最后一个页签标题的问题，关联@5035

src/jigsaw/pc-components/select/select-base.ts, src/ngx-formly/jigsaw/select/src/select-collpase.type.ts, src/ngx-formly/jigsaw/select/src/select-group.type.ts
=> [故障] 解决表单折叠下拉、分组下拉组件配置optionCount无效，以及在其多选时，选项校验有误的等问题；关联了@5012

src/jigsaw/pc-components/input/numeric-input.ts
=> [故障] 解决数字输入框在表单中使用时，清空值不会触发表单校验的问题，关联了@4792

src/app/for-internal/demo/pc/form/template-driven/demo.component.html, src/app/for-internal/demo/pc/form/template-driven/demo.component.ts, src/ngx-formly/jigsaw/select/src/select.type.ts
由于在表单中select组件是充满的，所以size属性没有效果，其他的都同步了。
=> [新增] 表单模块下select组件的增加manualSearch属性和searchKeywordChange事件，关联@4597

src/jigsaw/common/service/time.service.ts
=> [故障] 解决新版火狐浏览器下日期选择器箭头不生效的问题，关联了@WIB-163276
