- package.json
> 回退ts版本到2.3.2

- README.md
> Add Chinese name for Jigsaw

- src/rdk/component/tabs/tab.html
- src/rdk/component/tabs/tab.ts
> selectedIndex的变更检查修改&去掉路由注入

- docs/README.md
> # 添加collapse文档链接

- src/jigsaw/service/popup.service.ts
> #116 popup销毁优化

- src/jigsaw/component/list-and-tile/list.scss
- src/jigsaw/component/pagination/pagination.html
- src/jigsaw/component/pagination/pagination.scss
- src/jigsaw/component/radio/radio.scss
1.radio 小幅搓开
2.list没有背景
3.分页goto的input把字挡住了
fixes #196
> fix small mistake

- src/jigsaw/assets/scss/index.scss
- src/jigsaw/directive/scrollbar/scrollbar.ts
> scroll-bar roll back and fix #190

- src/app/e2e-testee/nav-info.ts
- src/app/e2e-testee/range-time/range-time-demo.module.ts
- src/app/live-demo/range-time/range-time-full/app.component.html
- src/app/live-demo/range-time/range-time-full/app.component.ts
- src/app/live-demo/range-time/range-time-full/app.module.ts
- src/app/live-demo/time/time-full/app.component.html
- src/jigsaw/assets/scss/index.scss
- src/jigsaw/component/range-time/range-time.html
- src/jigsaw/component/range-time/range-time.ts
修复range-time bug：
秒粒度时，范围时间无法显示到秒；
周粒度时，无法选择周的范围。
> range-time live demo and fix bug

- package.json
- src/app/e2e-testee/table/rendererOfTemplateRef/app.component.html
- src/app/e2e-testee/table/rendererOfTemplateRef/app.component.ts
- src/app/live-demo/table/renderer/app.component.html
- src/app/live-demo/table/renderer/app.component.ts
- src/app/live-demo/table/renderer/app.module.ts
- src/app/live-demo/table/renderer/renderers.ts
- src/jigsaw/component/table/table-inner.components.ts
- src/jigsaw/component/table/table.ts
> Template renderer cannot update cellData

- src/jigsaw/component/table/table.ts
> Fixes table cannot auto calculate column width 

- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/select/select.scss
- src/jigsaw/component/table/table.html
- src/jigsaw/component/table/table.ts
- src/jigsaw/package.json
fixes when table data change table cannot auto calculate column width
> Fix content width bug

- .travis.yml
- CONTRIBUTING.md
- package.json
- src/app/live-demo/range-time/range-time-full/app.component.ts
- src/app/live-demo/time/time-full/app.component.ts
- src/jigsaw/component/alert/alert.ts
- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/dialog/dialog.ts
- src/jigsaw/component/range-time/range-time.scss
- src/jigsaw/component/range-time/range-time.ts
- src/jigsaw/component/select/select.scss
- src/jigsaw/component/table/table.html
- src/jigsaw/component/table/table.ts
- src/jigsaw/package.json
- src/jigsaw/service/time.service.ts
> Fixes when grItem's gr is hour the rangeTime cannot work

- src/jigsaw/component/scrollbar/scrollbar.ts
- src/jigsaw/component/viewport/viewport.html
> Viewport bugs

- src/app/demo/fish-bone/full/app.component.ts
- src/jigsaw/component/chart-icon/chart-icon-factory.ts
> Chart icon feature

- src/app/app.interceptors.ts
- src/app/demo/table/checkbox-column-object-cell/app.component.html
- src/app/demo/table/checkbox-column-object-cell/app.component.ts
- src/app/demo/table/checkbox-column-object-cell/app.module.ts
- src/app/demo/table/checkbox-column/app.component.css
- src/app/demo/table/checkbox-column/app.component.html
- src/app/demo/table/checkbox-column/app.component.ts
- src/app/demo/table/checkbox-column/app.module.ts
- src/app/demo/table/checkbox-column/readme.md
- src/app/demo/table/demo.module.ts
> Table checkbox renderer demo and readme

- src/app/demo/table/local-paging-data/app.component.ts
- src/app/demo/table/pageable/app.component.html
- src/app/demo/table/pageable/app.component.ts
- src/app/demo/table/sortable/app.component.ts
- src/jigsaw/component/table/table-inner.components.ts
- src/jigsaw/core/data/component-data.ts
- src/jigsaw/core/data/table-data.ts
> Fixes PageableTableData can not sort

- .angular-cli.json
- build/tools/gulp/packaging/rollup-helpers.ts
- package.json
- src/app/demo/alert/customized/customized-alert.ts
- src/app/demo/dialog/in-dom/app.component.ts
- src/app/demo/scrollbar/basic/app.component.css
- src/app/demo/scrollbar/basic/app.component.html
- src/app/demo/scrollbar/basic/app.component.ts
- src/jigsaw/component/select/select.ts
- src/jigsaw/component/table/table.ts
- src/jigsaw/core/theming/prebuilt/settings/common.scss
> Update ngx scrollbar version

- src/app/demo/dialog/popup-option/app.component.ts
- src/jigsaw/component/input/input.ts
> Fixes popup option demo cannot set popup 'fixed position', and optimize input set value

- e2e/components/tabs.e2e-spec.ts
- src/jigsaw/component/table/table-inner.components.ts
- src/jigsaw/component/table/table.ts
> fix table sort

- src/app/demo/radio/basic/app.component.html
- src/app/demo/radio/basic/app.component.ts
- src/app/demo/radio/basic/app.module.ts
- src/jigsaw/component/radio/radio.ts
> fixes #269

- src/app/demo/table/renderer/renderers.ts
- src/jigsaw/component/table/table-renderer.ts
- src/jigsaw/core/data/general-collection.ts
> fixes #313

- src/jigsaw/component/time/time.ts
> fixes #316

- src/app/demo/tree/editable/app.component.ts
> fix treeData source

- src/jigsaw/component/input/input.scss
> delete input animation

- src/jigsaw/component/range-time/range-time.ts
- src/jigsaw/service/time.service.ts
> fixes #359

- src/app/demo/combo-select/open/app.component.html
- src/jigsaw/component/combo-select/combo-select.ts
> fixes #374

- src/app/demo/time/basic/app.component.html
- src/app/demo/time/basic/app.component.ts
- src/app/demo/time/basic/app.module.ts
- src/jigsaw/component/time/time.ts
> fixes #378

- src/app/demo/trusted-html/full/app.component.ts
> fixes #360

- src/jigsaw/directive/trusted-html/trusted-html.ts
> fixes #384

- e2e/components/i18n.e2e-spec.ts
- e2e/components/list.e2e-spec.ts
- e2e/components/loading.e2e-spec.ts
- e2e/components/slider.e2e-spec.ts
- e2e/components/tab.e2e-spec.ts
- e2e/components/tree.e2e-spec.ts
- protractor-config-for-components.js
- src/jigsaw/component/table/table.scss
> delete overflow-y and wait for review

- src/app/demo/table/calendar/app.component.ts
> "-" repalce to "/"

- src/jigsaw/component/switch/switch.scss
> fixes #386

- src/app/demo/combo-select/searchable/app.component.css
- src/app/demo/combo-select/searchable/app.component.html
- src/app/demo/combo-select/searchable/app.component.ts
- src/app/demo/combo-select/searchable/app.module.ts
- src/jigsaw/component/combo-select/combo-select.html
- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/combo-select/combo-select.ts
- src/jigsaw/component/tag/tag.ts
- src/jigsaw/core/utils/common-utils.ts
- src/jigsaw/service/popup.service.ts
> Combo support multi lines

- src/app/demo/drag-drop/table-drag/table-renderer.ts
- src/jigsaw/core/utils/common-utils.ts
- src/jigsaw/directive/dragdrop/draggable.ts
> fixes drag demo error

- src/jigsaw/component/select/select.ts
> destroy useless listen

- e2e/components/graph.e2e-spec.ts
用例此次执行了27秒多，报错说超过了DEFAULT_TIMEOUT_INTERVAL；
此次commit去掉了不少无用的await,会提速用例执行，避免超时
> fixes graph e2e spec

- src/jigsaw/component/table/table.ts
> table warn

- e2e/components/i18n.e2e-spec.ts
> fixes i18n

- src/jigsaw/component/combo-select/combo-select.ts
> fixes #434

- src/jigsaw/assets/scss/core/_mixin.scss
- src/jigsaw/assets/scss/index.scss
- src/jigsaw/component/button/button.scss
- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/list-and-tile/list-option.scss
- src/jigsaw/component/list-and-tile/tile-option.scss
- src/jigsaw/component/pagination/pagination.scss
- src/jigsaw/component/radio/radio.scss
- src/jigsaw/component/switch/switch.scss
- src/jigsaw/component/tabs/tab.scss
- src/jigsaw/component/time/time.scss
- src/jigsaw/core/theming/prebuilt/settings/antd.scss
- src/jigsaw/core/theming/prebuilt/settings/zte.scss
> fixes ie11 can not be compatible with text color of rgba

- src/app/demo/fish-bone/full/app.component.css
- src/app/demo/fish-bone/full/app.component.html
- src/app/demo/fish-bone/full/app.component.ts
- src/jigsaw/component/chart-icon/chart-icon-factory.ts
- src/jigsaw/component/fish-bone/fish-bone-item.scss
- src/jigsaw/component/fish-bone/fish-bone.scss
- src/mock-data/fish-bone-1.json
fixes #349
1.增加图例和饼图间距的配置
2.解决描述文字模糊问题，没有彻底清晰，优化了下
> Chart-icon & fish-bone feature

- src/jigsaw/component/tree/tree-ext.ts
> fixes #461

- src/jigsaw/component/table/table.html
> fixes #467

- src/app/app.interceptors.ts
- src/app/demo/table/pageable/demo.component.ts
- src/jigsaw/core/data/table-data.ts
> pageableTableData add post request

- src/app/app.interceptors.ts
> fixes #486

- src/app/demo/notification/full/demo.component.ts
- src/jigsaw/directive/trusted-html/trusted-html.ts
> fixes issue 503

- src/jigsaw/component/table/table.ts
> fixes #509

- src/jigsaw/component/table/table-inner.components.ts
- src/jigsaw/component/table/table.html
> fixes #508

- src/jigsaw/component/table/table-renderer.ts
- src/jigsaw/component/table/table.ts
> fixes #524

- src/jigsaw/component/box/box.ts
- src/jigsaw/component/box/common-box.ts
- src/jigsaw/component/box/editable-box.ts
- src/jigsaw/component/button/button.ts
- src/jigsaw/component/combo-select/combo-select.ts
- src/jigsaw/component/common.ts
- src/jigsaw/component/dialog/dialog.ts
- src/jigsaw/component/fish-bone/fish-bone.ts
- src/jigsaw/component/input/input.ts
- src/jigsaw/component/list-and-tile/group-common.ts
- src/jigsaw/component/pagination/pagination.ts
- src/jigsaw/component/range-time/range-time.ts
- src/jigsaw/component/scrollbar/scrollbar.ts
- src/jigsaw/component/table/table-inner.components.ts
- src/jigsaw/component/table/table.ts
- src/jigsaw/component/tabs/tab.ts
- src/jigsaw/component/time/time.ts
- src/jigsaw/directive/movable/movable.ts
> Clear timeout on destroy in every component

- src/jigsaw/component/combo-select/combo-select.ts
-  remove event listener as soon as possible;
- change close timeout to 400ms;
- change open timeout to 100ms;
> optimize change for combo-select

- build/scripts/doc-generator/generate.sh
- build/scripts/doc-generator/json-parser.js
- src/jigsaw/component/common.ts
> Doc parser

- src/jigsaw/component/combo-select/combo-select.ts
> fixes #539

- build/scripts/doc-generator/json-parser.js
> Add demo for api

- src/jigsaw/component/tree/tree-ext.ts
> fixes #500

- src/app/demo/time/with-combo-select/demo.component.html
- src/app/demo/time/with-combo-select/demo.component.ts
- src/jigsaw/assets/scss/index.scss
> fixes #563

- build/scripts/doc-generator/json-parser.js
- src/jigsaw/component/graph/graph.ts
- src/jigsaw/component/table/table-typings.ts
- src/jigsaw/core/data/array-collection.ts
- src/jigsaw/core/data/component-data.ts
- src/jigsaw/core/data/general-collection.ts
- src/jigsaw/core/data/graph-data.ts
- src/jigsaw/core/data/layout-data.ts
- src/jigsaw/core/data/table-data.ts
- src/jigsaw/core/data/tree-data.ts
- src/jigsaw/service/popup.service.ts
> Add more api doc

- build/scripts/doc-generator/json-parser.js
> add footer

- build/scripts/doc-generator/json-parser.js
- src/jigsaw/component/table/table-typings.ts
> 给废弃方法加样式和提示

- e2e/components/loading.e2e-spec.ts
- src/app/demo/popup/demo-set.module.ts
- src/app/demo/popup/z-index/demo.component.html
- src/app/demo/popup/z-index/demo.component.ts
- src/app/demo/popup/z-index/demo.module.ts
- src/jigsaw/component/box/box.scss
- src/jigsaw/component/box/editable-box.scss
- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/graph/graph.scss
- src/jigsaw/component/list-and-tile/list-option.scss
- src/jigsaw/component/notification/notification.scss
- src/jigsaw/component/notification/notification.ts
- src/jigsaw/component/select/select.scss
- src/jigsaw/component/slider/slider.scss
- src/jigsaw/component/table/table.scss
- src/jigsaw/component/tabs/tab.scss
- src/jigsaw/component/viewport/viewport.scss
- src/jigsaw/core/theming/prebuilt/settings/common.scss
- src/jigsaw/service/popup.service.ts
> 修改popup的z-index机制，重新整合皮肤的z-index

- src/app/demo/table/big-table/demo.component.html
- src/app/demo/table/big-table/demo.component.ts
- src/jigsaw/component/viewport/viewport.html
- src/jigsaw/component/viewport/viewport.ts
> fixes #608

- src/app/app.interceptor.ts
- src/app/demo/table/big-column/demo.module.ts
- src/app/demo/table/big-row/demo.module.ts
- src/app/demo/table/big-table/demo.component.html
- src/app/demo/table/big-table/demo.module.ts
- src/app/demo/table/renderer/demo.module.ts
- src/jigsaw/component/scrollbar/scrollbar.ts
- src/jigsaw/core/data/component-data.ts
- src/jigsaw/core/data/table-data.ts
> Fix bigtabledata really busy

- src/app/demo/graph/basic/demo.component.html
- src/app/demo/graph/basic/demo.component.ts
- src/jigsaw/component/graph/graph.ts
> fixes #644

- src/jigsaw/component/chart-icon/chart-icon-factory.ts
> fixes #648

- src/jigsaw/component/table/table.ts
> 表格在update的时候，自动标记已经设置的选中行

- src/jigsaw/component/table/table.ts
> fixes #698

- src/app/demo/list/full/demo.component.html
- src/jigsaw/component/list-and-tile/group-common.ts
- src/jigsaw/component/list-and-tile/list-option.html
- src/jigsaw/component/radio/radio.ts
> fixes #700

- src/app/demo/editable-box/custom-scene-layout/demo.component.html
- src/app/demo/editable-box/custom-scene-layout/demo.component.ts
- src/jigsaw/component/box/editable-box.html
- src/jigsaw/component/box/editable-box.scss
- src/jigsaw/component/box/editable-box.ts
- src/jigsaw/component/box/tabs-wrapper/tabs-wrapper.ts
> fixes #694 editable box add tab option bar

- src/app/demo/tab/basic/demo.component.html
- src/app/demo/tab/basic/demo.component.ts
- src/jigsaw/component/tabs/tab.ts
> fixes tabs can not listen selectedIndexChange and selectedChange

- src/jigsaw/component/table/table.ts
> [修复] columnDefine的data generate会导致table cell 渲染错误

- src/app/demo/upload/basic/demo.component.html
- src/app/demo/upload/basic/demo.component.ts
- src/app/demo/upload/basic/demo.module.ts
- src/jigsaw/component/upload/upload.html
- src/jigsaw/component/upload/upload.ts
> [新增] upload组件支持限制文件类型，上传失败的文件信息也能从组件传出来，fixes #717

- src/app/demo/box/demo-set.module.ts
- src/app/demo/box/view-init/demo.component.css
- src/app/demo/box/view-init/demo.component.html
- src/app/demo/box/view-init/demo.component.ts
- src/app/demo/box/view-init/demo.module.ts
- src/jigsaw/component/box/box.ts
> [新增]Box增加viewInit静态事件，用于监听box整体布局样式的初始化

- src/app/demo/table/cell-editable/demo.component.html
- src/app/demo/table/renderer/demo.component.html
- src/app/demo/table/switch-renderer/demo.component.html
- src/jigsaw/component/table/table.html
- src/jigsaw/component/table/table.ts
> [破坏性修改] 修改table的dataChange属性为edit，避免和data形成双绑

- src/jigsaw/component/input/numeric-input.ts
Change-Id: Ifaaa892d7d037cc8bee0a0c149c75e4a630312c0
> [修复] 修复numeric-input初始化时样式标红的问题

- src/jigsaw/component/tabs/index.ts
- src/jigsaw/component/tabs/tab.html
Change-Id: If3bf10d9dfa603e8ac05e12d8cb3d4b2fa40c7ab
> [修复] 删除tab自动滚动条，改由用户自己添加

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: I070e22461e6142cb773a3d942cd5238749a63ed1
> publish v1.1.13

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: I2ea1c5c498d5137a767db96a98dfcae5e473ac3a
> pre release v1.2.0-beta1

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: I9d2084b40ee6d3efcd0608ec99cf24450bbed92f
> publish v1.1.14

- src/jigsaw/component/list-and-tile/list-lite.scss
- src/jigsaw/component/list-and-tile/list-lite.ts
Change-Id: Ic9ec14405c041f10f5020152d54ce58274d5a32b
> [优化] list-lite添加invalid样式

- src/app/app.interceptor.ts
- src/app/demo/pagination/basic/demo.component.html
- src/app/demo/pagination/basic/demo.component.ts
- src/jigsaw/component/pagination/pagination.html
- src/jigsaw/component/pagination/pagination.scss
- src/jigsaw/component/pagination/pagination.ts
Change-Id: Ib79332215ba7235b1140924dc55764b1618102b9
> [新增] 分页组件增加mode属性，用于让分页支持精简版布局

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: Ie6cf05bf82066fe509e62e53a43fd0969f854b6e
> publish v1.1.15

- CHANGELOG.md
- src/app/app.interceptor.ts
- src/app/demo/transfer/pageable-array/demo.component.ts
- src/jigsaw/component/transfer/transfer-list.html
- src/jigsaw/package.json
Change-Id: I9217948645d9ee2e6e6c3e6c29c8689c31f2a861
> [修复] 修复在transfer中给pagination设置属性错误

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: I220e5db13d26a9b98053259f620c123d5bf2fad6
> pre-publish v1.2.0-beta2

- src/app/demo/list/full/demo.component.html
- src/app/demo/transfer/demo-set.module.ts
- src/app/demo/transfer/disabled/demo.component.html
- src/app/demo/transfer/disabled/demo.component.ts
- src/app/demo/transfer/disabled/demo.module.ts
- src/app/demo/transfer/i18n/demo.component.html
- src/app/demo/transfer/i18n/demo.component.ts
- src/app/demo/transfer/i18n/demo.module.ts
- src/app/demo/transfer/valid/demo.component.html
- src/app/demo/transfer/valid/demo.component.ts
- src/app/demo/transfer/valid/demo.module.ts
- src/jigsaw/component/list-and-tile/list.scss
- src/jigsaw/component/list-and-tile/list.ts
- src/jigsaw/component/transfer/transfer-list.html
- src/jigsaw/component/transfer/transfer.html
- src/jigsaw/component/transfer/transfer.scss
- src/jigsaw/component/transfer/transfer.ts
> 解决issue786中提到的穿梭框遗留的几个问题

- src/jigsaw/component/combo-select/combo-select.ts
- src/jigsaw/component/input/auto-complete-input.ts
- src/jigsaw/component/upload/upload.directive.ts
- src/jigsaw/service/popup.service.ts
> [新增] popup增加水平弹出位置矫正，当右边位置不够时，靠右对齐

- src/jigsaw/component/collapse/collapse-pane.html
- src/jigsaw/component/collapse/collapse.scss
- src/jigsaw/component/collapse/collapse.ts
> [优化] 优化collapse的展开动画，fixes #30

- src/app/demo/dialog/demo-set.module.ts
- src/app/demo/dialog/height/demo.component.css
- src/app/demo/dialog/height/demo.component.html
- src/app/demo/dialog/height/demo.component.ts
- src/app/demo/dialog/height/demo.module.ts
- src/jigsaw/component/button/button.scss
- src/jigsaw/component/button/button.ts
- src/jigsaw/component/dialog/dialog.html
- src/jigsaw/component/dialog/dialog.scss
- src/jigsaw/component/dialog/dialog.ts
- src/jigsaw/core/theming/prebuilt/zte.scss
> [新增] dialog现在可以设置弹框的高度

- src/jigsaw/component/dialog/dialog.scss
Change-Id: I15a03a6ad7ed71a21a481fa1e5e71ffea33b0e4b
> [修复] 修复dialog设置高度后，content部分的宽度无法正确获取

- src/jigsaw/component/tabs/tab.html
- src/jigsaw/component/tabs/tab.scss
- src/jigsaw/component/tabs/tab.ts
- src/jigsaw/core/theming/theming-api.scss
> [修复] 修改在加入滚动条后tab的样式问题，fixes #831

- src/jigsaw/component/combo-select/combo-select.scss
> [修复] 修复input在combo中有边框的问题

- src/jigsaw/component/combo-select/combo-select.scss
- src/jigsaw/component/pagination/page.scss
- src/jigsaw/component/pagination/pagination.scss
- src/jigsaw/component/transfer/transfer-list.html
- src/jigsaw/component/transfer/transfer.scss
- src/jigsaw/component/transfer/transfer.ts
- src/jigsaw/core/theming/prebuilt/settings/zte.scss
> [破坏性修改]修改皮肤的基础高度为32px,统一单行组件的高度，fixes#826

- src/app/demo/slider/demo-set.module.ts
- src/app/demo/slider/update/demo.component.css
- src/app/demo/slider/update/demo.component.html
- src/app/demo/slider/update/demo.component.ts
- src/app/demo/slider/update/demo.module.ts
- src/jigsaw/component/slider/slider.html
- src/jigsaw/component/slider/slider.ts
> [修复] 修复slider的value为数组时，改变value的元素不能更新视图的问题，fixes #840

- src/jigsaw/service/popup.service.ts
> [修复] popup无法在ie里矫正位置，fixes #850

- src/jigsaw/component/input/auto-complete-input.ts
- src/jigsaw/component/input/input.ts
- src/jigsaw/directive/movable/movable.ts
> [优化] 拖拽"交互动作"弹窗的框的时候，下拉框内容会脱离弹窗框而不是跟随移动

- src/app/demo/table/demo-set.module.ts
- src/app/demo/table/mixin-table/demo.component.html
- src/app/demo/table/mixin-table/demo.component.ts
- src/app/demo/table/mixin-table/demo.module.ts
- src/jigsaw/component/table/table.scss
- src/jigsaw/component/table/table.ts
Change-Id: I1b07689716bb6dffcf6f3993bf88430c88cfb9ef
> [优化] 优化对table内部嵌套含table的渲染器的支持，fixes #859

- src/jigsaw/component/list-and-tile/group-common.ts
> [修复] 修复radio在data异步获取，无法显示已有选中项的问题，fixes #823

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: Ic15cf51695d44245816fb2c51c66fda37a58a6bd
> publish v1.1.20

- src/jigsaw/component/input/auto-complete-input.ts
> [修复] 修复auto-compoment-input下拉报错的问题, fixes #876

- src/app/demo/drawer/drawer-in-drawer/demo.component.html
- src/app/demo/drawer/with-div/demo.component.html
- src/app/demo/drawer/with-div/demo.component.ts
- src/jigsaw/component/drawer/drawer.ts
> 抽屉的width/height支持一个快捷标志：auto,解决了 @994

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: Ie26e205f9ed8a7fd515dc8b2695d93c75378d7cd
> publish v1.1.21

- build/tools/gulp/packaging/build-release.ts
> [修复] 在node里面require jigsaw的的umd包时报错，fixes #889

- src/jigsaw/component/tabs/tab.html
- src/jigsaw/component/tabs/tab.scss
- src/jigsaw/component/tabs/tab.ts
Change-Id: I6090f12e999a14db6131f2f9dc179c9e5f337812
> [新增] tab增加enableAnimation属性，用于打开和关闭切换tab内容的动画

- src/jigsaw/component/input/auto-complete-input.html
- src/jigsaw/component/input/auto-complete-input.ts
Change-Id: I3503c49c7a280e65fac0f77f7c627fcd8f258f83
> [故障] 修复auto-input在float里面选择时，float也被关闭

- src/jigsaw/component/input/input.html
- src/jigsaw/component/input/input.scss
- src/jigsaw/component/input/numeric-input.scss
Change-Id: If978dbb55579d25fc1cddd7a1ae7bb2ec0275f4a
> [故障] v1.1修复input disable没有背景的问题

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: I6b05f2389ff65c84af325a2809107bef802a6493
> 散点图可视化数据类型

- src/jigsaw/common/core/data/modeled-graph-data.ts
- src/jigsaw/common/core/utils/data-collection-utils.ts
Change-Id: I16a64ee7819d047cda55b6f66743b4425720e4bb
> 修复仪表盘和散点图数据的多维度问题

- src/jigsaw/pc-components/graph/graph.html
- src/jigsaw/pc-components/graph/graph.ts
Change-Id: I961b2ce84653a3dd00dab91e508b48743ae695e2
> [修复] 修复graph设置visibility:hidden无法隐藏图形的问题

- src/app/demo/pc/combo-select/demo-set.module.ts
- src/app/demo/pc/combo-select/height/demo.component.html
- src/app/demo/pc/combo-select/height/demo.component.ts
- src/app/demo/pc/combo-select/height/demo.module.ts
- src/jigsaw/pc-components/combo-select/combo-select.html
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/combo-select/index.ts
Change-Id: Id589ec927f3ee5baad455d94c05174e9ee9fe082
> [新增] combo-select支持设置height，支持多行滚动显示

- src/app/demo/pc/combo-select/demo-set.module.ts
- src/app/demo/pc/combo-select/height/demo.component.html
- src/app/demo/pc/combo-select/height/demo.component.ts
- src/app/demo/pc/combo-select/height/demo.module.ts
- src/jigsaw/pc-components/combo-select/combo-select.html
Change-Id: Id049511edeb6a0d44a26c706d962c09059afab16
> [优化] combo-select的height属性改成maxHeight

- src/jigsaw/core/data/array-collection.ts
- src/jigsaw/core/data/table-data.ts
Change-Id: I192fe48f976b8aef4a4310099f7bcf13dd083966
> [修复] 修复无法使用服务端分页排序的问题

- src/jigsaw/common/core/data/array-collection.ts
- src/jigsaw/common/core/data/table-data.ts
Change-Id: I58e20380d8dc716e70f5fa4d53802641dc80b5e0
> [修复] 修复无法使用服务端分页时排序的问题

- CHANGELOG.md
- src/jigsaw/package.json
Change-Id: I5150a7a854a5731db2b9783fed385152335df350
> publish v1.1.26

- src/jigsaw/pc-components/tabs/tab.ts
Change-Id: I145e43d774a1de727de082cc5790a2684fb300b4
> [优化] 优化多tab嵌套性能问题

- src/jigsaw/pc-components/tabs/tab.ts
Change-Id: I1771c6a3a41b55147df98cb2a1d39e08fbd7ef96
> [故障] 修复无法准确根据tab的高度计算tab-content高度的问题

- src/jigsaw/pc-components/table/table-inner.components.ts
Change-Id: Ie4ad4a486da6535468c3f4c4ea6e2b9a90459fd4
> [故障] table表头排序按钮与文字重叠，fixes #623, #663

- src/app/demo/pc/table/sortable/demo.component.html
- src/app/demo/pc/table/sortable/demo.component.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
- src/jigsaw/pc-components/table/table.ts
Change-Id: I7793562909c274f20b46165192705a93a37e9f1c
> [新增] 增加手动重置table排序按钮状态的功能

- src/app/demo/pc/dialog/height/demo.component.css
- src/app/demo/pc/dialog/height/demo.component.html
- src/app/demo/pc/dialog/height/demo.module.ts
- src/jigsaw/pc-components/dialog/dialog.scss
Change-Id: I5858867fe3a9f33c60754dfe61f5415b9f7438f2
> [故障] dialog固定高度时，内容太高被撑开，无法产生纵向滚动条

- src/jigsaw/pc-components/range-time/range-time.ts
Change-Id: I00059fe4d401cce333224a1bde37bd54fb3ae212
> [故障] 修复range-time无法初始化显示周范围

- CHANGELOG.md
- src/jigsaw/pc-components/package.json
Change-Id: I740c5049c54e1a22e57be0cd73601ae85d15a8d4
> publish v5.0.1

- CHANGELOG.md
- src/jigsaw/pc-components/package.json
Change-Id: I14c4bbb7de4241936be164429e922aeb30282e05
> publish v8.0.1

- src/jigsaw/pc-components/tabs/tab.html
- src/jigsaw/pc-components/tabs/tab.scss
- src/jigsaw/pc-components/tabs/tab.ts
Change-Id: I42022d7ae1ae3958b514436be736dc295a25ec40
> [优化] 优化tab的垂直响应

- src/app/demo/pc/tree/async/demo.component.ts
- src/app/demo/pc/tree/basic/demo.component.ts
- src/app/demo/pc/tree/custom-settings-callback/demo.component.ts
- src/app/demo/pc/tree/data-from-ajax/demo.component.ts
- src/app/demo/pc/tree/editable/demo.component.ts
- src/jigsaw/common/core/data/tree-data.ts
- src/jigsaw/pc-components/tree/tree-ext.ts
Change-Id: I33b0e189c8ce102d1cf2cb71f0e746733c57cf1d
> [新增] 增加SimpleTreeData数据类型，代替TreeData作为JigsawTreeExt的数据，以应对TreeData的性能问题

- docs/jigsaw-design-concept/index.md
- src/app/demo/pc/cascade/basic/demo.component.ts
- src/app/demo/pc/cascade/multiple-select/demo.component.ts
- src/app/demo/pc/cascade/selected-items/demo.component.ts
- src/app/demo/pc/cascade/show-all/demo.component.ts
- src/app/demo/pc/cascade/track-item-by/demo.component.ts
- src/app/demo/pc/fish-bone/full/demo.component.ts
- src/jigsaw/common/core/data/component-data.ts
- src/jigsaw/common/core/data/tree-data.ts
- src/jigsaw/pc-components/cascade/cascade.ts
- src/jigsaw/pc-components/fish-bone/fish-bone.ts
Change-Id: Ia7650a78f8fb9cda8aa6740f757a53cb6dba2165
> [优化] cascade、fishbone的数据换成SimpleTreeData

- docs/jigsaw-design-concept/index.md
- src/app/demo/cascade/basic/demo.component.ts
- src/app/demo/cascade/multiple-select/demo.component.ts
- src/app/demo/cascade/selected-items/demo.component.ts
- src/app/demo/cascade/show-all/demo.component.ts
- src/app/demo/cascade/track-item-by/demo.component.ts
- src/app/demo/fish-bone/full/demo.component.ts
- src/app/demo/tree/async/demo.component.ts
- src/app/demo/tree/basic/demo.component.ts
- src/app/demo/tree/custom-settings-callback/demo.component.ts
- src/app/demo/tree/data-from-ajax/demo.component.ts
- src/app/demo/tree/editable/demo.component.ts
- src/jigsaw/component/cascade/cascade.ts
- src/jigsaw/component/tree/tree-ext.ts
- src/jigsaw/core/data/component-data.ts
- src/jigsaw/core/data/tree-data.ts
> [新增] 增加SimpleTreeData数据类型，代替TreeData作为JigsawTreeExt、cascade、fishbone的数据，以应对TreeData的性能问题

- src/app/demo/pc/table/pageable/demo.component.ts
- src/app/demo/pc/table/sortable/demo.component.html
- src/app/demo/pc/table/sortable/demo.component.ts
- src/app/demo/pc/table/sortable/demo.module.ts
- src/jigsaw/common/core/data/table-data.ts
- src/jigsaw/pc-components/table/table.ts
- src/jigsaw/pc-components/textarea/textarea.scss
Change-Id: I09d7b39ea06784ea938e01beeb09fea2ba8bfdb5
> [新增] table默认排序功能，fixes #582

- src/app/demo/pc/select/searchable/demo.component.ts
- src/jigsaw/pc-components/list-and-tile/group-common.ts
Change-Id: Ifa161c71ecdb8c566782d5a6a5d91074ca425abd
> [故障] list-lite会发送多余的selectItemChange事件

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: I2fd67868f621dac71735f142a9e39cf0d5053bc8
> [新增] 直角系数据模型对无dim的支持

- src/app/demo/pc/numeric-input/basic/demo.component.html
- src/app/demo/pc/numeric-input/basic/demo.component.ts
- src/jigsaw/pc-components/input/numeric-input.html
- src/jigsaw/pc-components/input/numeric-input.ts
Change-Id: Icf81ff13caed990f054bffdb82cc84463409ec35
> [故障] 修复numeric输出的值变成了字符串，优化通过输入框输入数字的交互

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: I95bb46a0d16d75b86bb48b5cac07e23ba4c3e433
> [故障] 修改直角系图形设置dimDisabled依旧会有dim的问题

- src/jigsaw/common/core/theming/theming-api.scss
- src/jigsaw/pc-components/input/auto-complete-input.ts
- src/jigsaw/pc-components/input/input.html
- src/jigsaw/pc-components/input/input.scss
- src/jigsaw/pc-components/input/input.ts
- src/jigsaw/pc-components/input/numeric-input.scss
- src/jigsaw/pc-components/input/numeric-input.ts
- src/styles.scss
Change-Id: Ie4113266c4bf0a29e0e4b68a514c14f8b5185536
> [优化] JigsawInput系组件性能优化

- src/app/demo/pc/table/html-renderer/demo.component.ts
- src/jigsaw/pc-components/table/table-typings.ts
- src/jigsaw/pc-components/table/table-utils.ts
- src/jigsaw/pc-components/table/table.html
- src/jigsaw/pc-components/table/table.ts
> [新增] table在columnDefine中的header现在可以设置html作为表头的渲染器

- src/app/demo/pc/button-bar/basic/demo.component.html
- src/jigsaw/pc-components/list-and-tile/button-bar.ts
- src/jigsaw/pc-components/list-and-tile/tile-lite.ts
Change-Id: I7fa4c1105886754161314d985ffebe7a925ea688
> [新增] tile-lite和button-bar增加title提示文字

- src/jigsaw/pc-components/graph/graph.ts
Change-Id: I26ee5bace08a296cf7de4b3889b3418f10eccd87
> [优化] 当graph的宿主没有尺寸时，缩放浏览器不自动resize

- src/jigsaw/common/core/theming/echarts-theme.ts
Change-Id: Idd2c655c825331d7ac5a48275b11ed763b364844
> [优化] 调整graph颜色，增加不同系列的对比，fixes #1109

- src/jigsaw/pc-components/graph/graph.ts
Change-Id: I8c6bad73228c3e81dcce946d2601165356b7188e
> [修复] 修复window获取不到echarts对象的破坏性，fixes #1111

- src/app/demo/pc/cascade/basic/demo.component.html
- src/jigsaw/pc-components/cascade/cascade.ts
Change-Id: I7b8346d90db9aaec9905b756bae1a54a6489f99e
> [新增] cascade增加对内部tile option宽度的配置

- src/jigsaw/pc-components/input/auto-complete-input.ts
Change-Id: Ie3e087cfa05b2480abcdb08052444f0742cf4b1d
> [修复] 修复auto-complete没有下拉数据时会报错

- src/app/demo/pc/pagination/basic/demo.component.html
- src/app/demo/pc/pagination/basic/demo.component.ts
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.scss
- src/jigsaw/pc-components/pagination/pagination.ts
> [新增] 分页简单模式增加选择分页功能

- src/app/demo/pc/table/html-renderer/demo.component.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
- src/jigsaw/pc-components/table/table.html
> [优化] table header使用html渲染器同时也可以设置排序功能

- src/app/demo/pc/table/cell-render/demo.module.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: Ide6e32d4c9619d969231afc315cf2c35bfae7505
> [优化] 表格select渲染器退出编辑优化

- src/app/demo/pc/auto-complete-input/basic/demo.component.html
- src/app/demo/pc/auto-complete-input/basic/demo.component.ts
- src/app/demo/pc/table/cell-editable/demo.component.ts
- src/jigsaw/pc-components/input/auto-complete-input.html
- src/jigsaw/pc-components/input/auto-complete-input.ts
- src/jigsaw/pc-components/table/table-renderer.ts
- src/jigsaw/pc-components/table/table.ts
- src/jigsaw/pc-components/upload/upload.base.ts
Change-Id: I1c516f7ede1168ff619f87f7ff096b2636d4783e
> [新增] 增加表格的编辑单元格auto-complete渲染器

- src/app/demo/pc/table/cell-editable/demo.component.ts
- src/app/demo/pc/table/switch-renderer/demo.component.html
- src/app/demo/pc/table/switch-renderer/demo.component.ts
- src/app/demo/pc/table/switch-renderer/demo.module.ts
- src/jigsaw/pc-components/switch/switch.scss
- src/jigsaw/pc-components/switch/switch.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I26d28cc88a7a139aa0008e596875d718630d79ca
> [新增] 增加switch的只读模式

- src/tsconfig.app.json
Change-Id: I5bc535db2c2c46e39d3ca829b5e39700775d5ca3
> [故障] 修复元素之间默认边距消失的问题

- src/jigsaw/common/assets/scss/animate.scss
Change-Id: I38a2168dc5416c8831a133473a1ba27a42a3dd99
> [优化] 进度条动画优化

- src/jigsaw/pc-components/module.ts
Change-Id: I0ee26dcf6371af348a1a8340def2b1569d1c9442
> JigsawProgressModule添加到JigsawModule

- src/jigsaw/common/core/data/table-data.ts
Change-Id: Ia83f740d16313b4c5b45a8eb38e53d0619de5c1e
> [故障] 修复TreeData无法通过ajax获取数据

- src/jigsaw/pc-components/progress/progress.ts
Change-Id: I665785db6a07baa86248f434750b6635858035ef
> [优化] 弹出顶部进度条现在会销毁之前的，修复组件实例给status赋值无法更新视图

- src/jigsaw/pc-components/tabs/tab.ts
> tab宽度缩小到比title还窄时页面卡死问题

- src/jigsaw/pc-components/select/select.ts
> 回退select控件在OnInit事件中writeValue的修改

- src/jigsaw/pc-components/collapse/collapse.ts
> 解决折叠的手风琴模式不生效的问题

- src/app/demo/pc/progress/full/demo.component.html
- src/jigsaw/pc-components/progress/progress.html
- src/jigsaw/pc-components/progress/progress.scss
- src/jigsaw/pc-components/progress/progress.ts
> [优化] 优化不同状态下进度条的布局

- src/jigsaw/pc-components/range-time/range-time.ts
> [故障] 时间范围的span没有精确到时分秒

- src/app/demo/pc/auto-complete-input/basic/demo.component.html
- src/app/demo/pc/auto-complete-input/basic/demo.component.ts
- src/jigsaw/pc-components/input/auto-complete-input.html
- src/jigsaw/pc-components/input/auto-complete-input.ts
> [新增] autoInput组件添加maxDropDownWidth属性，可以设置弹出的最大宽度

- src/app/demo/pc/range-time/week-select/demo.component.html
- src/app/demo/pc/range-time/week-select/demo.component.ts
- src/app/demo/pc/range-time/week-select/demo.module.ts
- src/app/demo/pc/time/week-select/demo.component.html
- src/app/demo/pc/time/week-select/demo.component.ts
- src/app/demo/pc/time/week-select/demo.module.ts
- src/jigsaw/common/service/time.service.ts
- src/jigsaw/pc-components/range-time/range-time.html
- src/jigsaw/pc-components/range-time/range-time.ts
- src/jigsaw/pc-components/time/time.ts
> [新增] 时间控件支持设置周开始

- src/jigsaw/pc-components/cascade/cascade.ts
- src/jigsaw/pc-components/combo-select/combo-select.ts
- src/jigsaw/pc-components/input/auto-complete-input.html
- src/jigsaw/pc-components/input/auto-complete-input.ts
- src/jigsaw/pc-components/input/input.html
- src/jigsaw/pc-components/input/input.ts
- src/jigsaw/pc-components/input/numeric-input.html
- src/jigsaw/pc-components/input/numeric-input.ts
- src/jigsaw/pc-components/select/select.ts
- src/jigsaw/pc-components/textarea/textarea.html
- src/jigsaw/pc-components/textarea/textarea.ts
> [破坏性修改]控件在赋了初始值时，默认不触发change事件

- src/app/demo/pc/date-time-picker/date-time-select/demo.component.html
- src/app/demo/pc/range-date-time-picker/range-date-time-select/demo.component.html
- src/jigsaw/pc-components/date-and-time/date-picker.scss
- src/jigsaw/pc-components/date-and-time/date-time-picker.scss
- src/jigsaw/pc-components/date-and-time/date-time-select.scss
- src/jigsaw/pc-components/date-and-time/date-time-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
Change-Id: I710602077f21ec4bc0f5b1c732a351e5a48df4d0
> [故障] 修复部分日期时间组件没有白背景，date-select组件无法设置尺寸

- src/jigsaw/pc-components/date-and-time/date-picker.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-picker.ts
> [故障] 处理无效的weekDate，以及提前设置weekStart

- src/jigsaw/pc-components/date-and-time/date-picker.ts
Change-Id: If06e7361d7dcb78c5b70cb90e94b4392320ff0ac
> [故障] 修复日期控件limitEnd小于limitStart时页面卡死

- src/jigsaw/pc-components/date-and-time/range-date-time-picker.html
> [故障] 修复没有初始值时，时间范围选择器显示limitStart&limitEnd不正确

- src/jigsaw/pc-components/date-and-time/date-picker.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-picker.ts
> [故障] 修复日期范围选择器limit和周粒度一起用时无法发送change事件

- src/app/demo/table/pageable/demo.component.html
- src/app/demo/table/pageable/demo.component.ts
- src/app/demo/table/pageable/demo.module.ts
- src/jigsaw/component/pagination/pagination.html
- src/jigsaw/component/pagination/pagination.ts
> [新增] 分页组件增加searchDebounce，用于给搜索增加防抖和敲击回车键立刻搜索功能

- src/jigsaw/pc-components/notification/notification.ts
> [故障] 消息框弹出位置计算错误 

- src/jigsaw/pc-components/menu/menu.scss
- src/jigsaw/pc-components/menu/menu.ts
> 修复menu组件在图标为iconfont的时候，背景色错位的问题

- src/jigsaw/pc-components/input/input.html
- src/jigsaw/pc-components/input/numeric-input.html
> input设置autocomplete属性为off

- src/app/demo/pc/time-picker/step/demo.component.html
- src/jigsaw/pc-components/date-and-time/time-picker.ts
Change-Id: Id0161c27d22c3c49d9c025e24bf7002372782735
> [新增] time-picker支持15分钟30分钟粒度

- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
Change-Id: I034e2a73b27d2ed1c37232bae53378cbafc4221a
> [故障] 修复range-date-time-select同时修改日期和粒度时，计算日期不正确

- src/app/demo/pc/date-time-picker/date-time-select/demo.component.html
- src/app/demo/pc/date-time-picker/date-time-select/demo.component.ts
- src/app/demo/pc/date-time-picker/date-time-select/demo.module.ts
- src/app/demo/pc/range-date-time-picker/range-date-time-select/demo.component.html
- src/app/demo/pc/range-date-time-picker/range-date-time-select/demo.component.ts
- src/app/demo/pc/range-date-time-picker/range-date-time-select/demo.module.ts
- src/jigsaw/pc-components/date-and-time/date-time-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
Change-Id: I95b9a5f343290cecb2627ff0e7a30aa63211255f
> [故障] 修改date-time-select不支持同时修改多个属性

- src/jigsaw/common/core/theming/theming-api.scss
- src/jigsaw/pc-components/date-and-time/date-picker.scss
Change-Id: I2b0e685a4d1f653e7952b52d8a1cfa4220209400
> [优化] 优化日期控件在暗色皮肤下的样式

- src/jigsaw/pc-components/date-and-time/date-time-picker.ts
- src/jigsaw/pc-components/date-and-time/date-time-select.ts
Change-Id: I334497e8f9a479aa69caaed57c5b06583ede1ca2
> [故障] 修复先设置周粒度再设置日期会导致日期计算错误的问题

- src/app/app.interceptor.ts
- src/jigsaw/component/upload/upload.base.ts
Change-Id: I88915a8a024bd331daaa146d4559dffea92d835e
> [优化] upload兼容ie11

- src/jigsaw/pc-components/table/table-inner.components.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I0cd7f1861f9acce44667fe5fff513c9956cc9fe0
> [故障] 修复表格翻页时checkbox选择计算错误

- src/app/demo/pc/table/cell-editable-property/demo.component.html
- src/app/demo/pc/table/cell-editable-property/demo.component.ts
- src/jigsaw/pc-components/input/input.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I43594813a8d2a16214dd51d3b1aa822d4967d616
> [新增] 表格密码渲染器

- src/app/demo/pc/button/full/demo.component.html
- src/jigsaw/pc-components/button/button.html
- src/jigsaw/pc-components/button/button.ts
Change-Id: I5e31620fefb55ed6c9ff2576a8773bebd72febdc
> [新增] 按钮配置图标属性

- src/app/demo/pc/table/tree-table/demo.component.html
- src/app/demo/pc/table/tree-table/demo.component.ts
- src/jigsaw/common/core/data/table-data.ts
Change-Id: Ic56b9b2170e5a83fa65eb7a25020da52af381aa2
> [新增] 树表的过滤功能

- src/jigsaw/common/core/data/modeled-graph-data.ts
- src/jigsaw/pc-components/input/input.ts
Change-Id: I338fe18c81a6bd0d4a13caca19da36a7d29e2ccc
> [新增] 可视化图形增加配置单个系列颜色，修复输入框值为undefined时无法改变原有值

- src/jigsaw/pc-components/pagination/pagination.ts
Change-Id: Id2e779ddb30a1b9b3f822c1746dd8d8f9bcc1e46
> [故障] 分页的pageSize选择器显示为null/页，鼠标hover上去才能显示正确

- src/jigsaw/common/core/theming/echarts-theme.ts
Change-Id: I3bb40d16aa65ae0aa892ea0aebbb37e523019497
> [故障] 修复配置了图形Y轴name却不显示

- src/jigsaw/pc-components/date-and-time/date-time-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
- src/jigsaw/pc-components/input/input.ts
- src/jigsaw/pc-components/select/select.ts
Change-Id: I37f0f7c4dd742a19ff8711ed34c6c27a8660644e
> [故障] 修复一些组件通过实例赋值输入属性时视图不更新

- src/jigsaw/pc-components/table/renderer.scss
- src/jigsaw/pc-components/table/table-renderer.ts
> 【补丁】表格拖拽p标签样式补丁

- src/jigsaw/pc-components/cascade/cascade.ts
- src/jigsaw/pc-components/color-select/color-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-picker.ts
- src/jigsaw/pc-components/date-and-time/time-picker.ts
- src/jigsaw/pc-components/list-and-tile/group-lite-common.ts
- src/jigsaw/pc-components/list-and-tile/list-lite.ts
- src/jigsaw/pc-components/radio/radio-lite.ts
- src/jigsaw/pc-components/rate/rate.ts
- src/jigsaw/pc-components/textarea/textarea.ts
- src/jigsaw/pc-components/transfer/transfer.ts
Change-Id: Ibdda8fbea9b478d793b6c771843e3e162fb41b51
> [故障] 修复一些通过直接改变属性值不更新视图的组件

- src/jigsaw/pc-components/date-and-time/time-picker.ts
Change-Id: I5076034b1ea404129106fe63881e45704d189155
解决Timepicker limit 输入 个位数时功能错误问题。
> 解决Issue#2348

- src/jigsaw/pc-components/date-and-time/date-time-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
Change-Id: I85997ef529da82af60663227986280bbb6dec1b7
> [故障] 修复下拉时间设置firstWeekMustContains在未打开下拉计算第几周还是默认周数

- src/jigsaw/pc-components/dialog/dialog.scss
Change-Id: Ib7b440fb8c284c37bcf7ca784eeb1a6d70c32ee0
> [修复] Issue #2374

- src/app/demo/pc/list-lite/line-ellipsis/demo.component.ts
- src/jigsaw/pc-components/list-and-tile/list-lite.scss
- src/jigsaw/pc-components/list-and-tile/list-option.scss
Change-Id: I12302f92a2c2f1b2544d7dbc1a0728d9515adddd
> [修复] list-lite组件超出文本可正常显示省略号

- src/jigsaw/pc-components/transfer/transfer.scss
Change-Id: I2db284a22fb5e22b25f19843850e73098d6a8c77
- 去除整体的边框
> [新增] Transfer组件功能对齐

- src/jigsaw/pc-components/list-and-tile/tile.scss
Change-Id: I364dbf179616367e128020761affa1aad00747c1
- https://gitlab.zte.com.cn/10045812/ng-eval/issues/2397
> [修复] ButtonBar组件添加最大宽度

- src/app/demo/pc/table/calendar/demo.component.ts
- src/app/demo/pc/table/sudoku/number-renderer.ts
Change-Id: I1529d5cc9f3e2160cf15fca78885829f5da0f0b1
> [修复] 表格calendar和数独demo样式问题修复

- src/app/demo/pc/box/form/demo.component.html
Change-Id: I005c60f94497fd443f176eea341ab68b846e6ec8
> [修复] box/form demo界面弹性比例调整

- package.json
- src/jigsaw/pc-components/package.json
Change-Id: Ib59d85303169a7f1c5315b4006a296a090df6f0d
> [优化] 升级echarts依赖包版本至4.9.0

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
Change-Id: Ib107a5ddb3b2c428ae819efb82345d3d4c426a05
hsla色值的A：Alpha透明度。取值0~1之间。
> [修复] 修复组件的阴影太浓问题

- src/jigsaw/pc-components/notification/notification.html
- src/jigsaw/pc-components/notification/notification.scss
- src/jigsaw/pc-components/notification/notification.ts
> [新增] notification组件功能对齐

- src/app/demo/pc/table/update-column-defines/demo.component.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
Change-Id: Ifa30975e49ef6b1ca9aa056c6afabf64953fff3e
> [故障] 修复动态更新columnDefines有时会使表头文本无法显示

- src/app/demo/pc/button/disabled/demo.component.html
- src/jigsaw/pc-components/button/button.scss
Change-Id: I2463f44338faa194c94bf3148b5ea3ed6030a646
> [新增] button组件功能对齐

- src/jigsaw/pc-components/date-and-time/time-section.ts
Change-Id: Iaf410f4caadcba062047a4cbc66af965ce317edb
> [新增] Time-section组件增加“按天”选项

- src/jigsaw/pc-components/date-and-time/date-picker.ts
Change-Id: I925084b7a96de903e669d2e6b8ee0268f684fd1b
> [故障] 下拉日期时间无法根据translateService的语言设置

- src/app/demo/pc/progress/circle-progress/demo.component.html
- src/app/demo/pc/progress/circle-progress/demo.component.scss
- src/app/demo/pc/progress/circle-progress/demo.component.ts
- src/app/demo/pc/progress/circle-progress/demo.module.ts
- src/app/demo/pc/progress/demo-set.module.ts
- src/app/demo/pc/progress/full/demo.component.html
- src/app/demo/pc/progress/full/demo.component.ts
- src/jigsaw/pc-components/module.ts
- src/jigsaw/pc-components/progress/base.ts
- src/jigsaw/pc-components/progress/circle-progress.html
- src/jigsaw/pc-components/progress/circle-progress.scss
- src/jigsaw/pc-components/progress/circle-progress.ts
- src/jigsaw/pc-components/progress/progress.scss
- src/jigsaw/pc-components/progress/progress.ts
- src/jigsaw/pc-components/theming/all-theme.scss
- src/jigsaw/public_api.ts
> [新增] progress组件功能对齐

- src/jigsaw/pc-components/date-and-time/time-section.ts
Change-Id: I74341c3a800eacf8150562055b1cbce3ad335103
> [故障] 时间段选择器在页面报错，导致其他组件无法渲染

- src/app/demo/pc/slider/basic/demo.component.html
- src/app/demo/pc/slider/basic/demo.component.ts
- src/jigsaw/pc-components/slider/slider.html
- src/jigsaw/pc-components/slider/slider.ts
Change-Id: I4bf4c8bc78c2f8486f439fefc58cb4790bb47fb2
https://gitlab.zte.com.cn/10045812/ng-eval/issues/2542
> [优化] Slider组件mark未在范围内时呈灰色状态

- src/jigsaw/pc-components/transfer/transfer.scss
Change-Id: I9ea6c18c646331c893a5939ce6dc9fd1b8d94d28
> [优化] Transfer组件搜索框边距对齐规范

- src/app/demo/pc/date-picker/mark/demo.component.html
- src/app/demo/pc/date-picker/mark/demo.component.scss
- src/app/demo/pc/date-picker/mark/demo.component.ts
- src/jigsaw/pc-components/date-and-time/date-picker.scss
- src/jigsaw/pc-components/date-and-time/time-picker.html
- src/jigsaw/pc-components/date-and-time/time-picker.scss
- src/jigsaw/pc-components/date-and-time/time-pop.scss
Change-Id: I3b3ee4196dbd600e7f9d0e218e38d7f707e15522
> [优化] datepicker组件对齐样式

- src/app/demo/pc/radio-lite/demo-set.module.ts
- src/app/demo/pc/radio-lite/type/demo.component.html
- src/app/demo/pc/radio-lite/type/demo.component.ts
- src/app/demo/pc/radio-lite/type/demo.module.ts
- src/jigsaw/common/core/utils/common-utils.spec.ts
- src/jigsaw/common/core/utils/common-utils.ts
- src/jigsaw/pc-components/radio/radio-lite.ts
- src/jigsaw/pc-components/radio/radio.scss
- src/jigsaw/pc-components/radio/radio.ts
Change-Id: I997e404c60351da5e4825ae55366c246750d0a7a
https://gitlab.zte.com.cn/10045812/ng-eval/issues/2544
> [优化] radio组件新增四种状态

- src/jigsaw/pc-components/rate/rate.scss
- [rate](http://localhost:4200/#/pc/rate/full)
> [优化] rate组件间隔根据规范缩小

- src/app/demo/pc/switch/basic/demo.component.html
- src/app/demo/pc/switch/basic/demo.component.scss
- src/app/demo/pc/switch/basic/demo.component.ts
- src/app/demo/pc/switch/basic/demo.module.ts
- src/app/demo/pc/switch/demo-set.module.ts
- src/app/demo/pc/switch/size/demo.component.html
- src/app/demo/pc/switch/size/demo.component.scss
- src/app/demo/pc/switch/size/demo.component.ts
- src/app/demo/pc/switch/size/demo.module.ts
- src/jigsaw/pc-components/switch/switch.scss
- src/jigsaw/pc-components/switch/switch.ts
Change-Id: Idf6321641ba8e6a73c0c5588bbb55f36789aed95
https://gitlab.zte.com.cn/10045812/ng-eval/issues/2546
> [优化] switch组件新增3种高度规范；组件颜色规范对齐；解决了@7454

- src/app/demo/pc/table/checkbox-column/demo.component.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I1e778393ee01b19d587da67b25733e6bce572869
> [新增] 表格checkbox渲染器支持不可点击

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: I4cd3633d9cc6a58eae2978583c2df82d4fec56d6
> [新增] 增加可视化饼图图例数据源的配置

- src/app/demo/pc/icon/basic/demo.component.html
- src/jigsaw/pc-components/icon/icon.html
- src/jigsaw/pc-components/icon/icon.scss
- src/jigsaw/pc-components/icon/icon.ts
Change-Id: I6503063a25f9f5baea892072e274da109db9d5bb
http://localhost:4200/#/pc/icon/basic
> [优化] 增加图标位置在右侧和底部的配置，解决了@7419

- src/app/demo/pc/select/multiple/demo.component.html
- src/app/demo/pc/select/multiple/demo.component.ts
- src/jigsaw/pc-components/select/select.ts
Change-Id: I48ac405a3a67bc5b35a8de94be121a9e5ff7e8c3
> [故障] 修复多选下拉组件点击清除按钮时页面卡死，关联@7391

- src/app/demo/pc/cascade/basic/demo.component.html
- src/jigsaw/pc-components/cascade/cascade.scss
- src/jigsaw/pc-components/list-and-tile/list-option.scss
- src/jigsaw/pc-components/list-and-tile/tile.scss
http://localhost:4200/#/pc/cascade/basic
> [优化] 级联组件样式与规范对齐，解决了@7712

- src/jigsaw/pc-components/checkbox/checkbox.scss
- src/jigsaw/pc-components/theming/all-theme.scss
- src/jigsaw/pc-components/tree/tree-ext.ts
- src/jigsaw/pc-components/tree/tree.scss
Change-Id: I1597baab937dcd9ee726b2350f2b78f21867b857
http://localhost:4200/#/pc/tree/basic
> [优化] tree组件中除了竖线外的其他图标更改为iconfont，解决了@7673

- src/jigsaw/common/core/utils/common-utils.spec.ts
- src/jigsaw/common/core/utils/common-utils.ts
Change-Id: I5ca5ce07aae80a0d3b1212add63f150948fe9d30
> [故障] 修复图形设置双坐标配置补丁时图形坐标重合了，关联了@7371

- src/app/demo/pc/table/checkbox-column-pageable/demo.component.html
- src/app/demo/pc/table/checkbox-column-pageable/demo.component.ts
- src/jigsaw/pc-components/table/table.ts
Change-Id: I10b12b332f014036353b55f92fd6db15ea6e8054
> [故障] 服务端分页带搜索功能时，复选框选择行报错，关联@7369

- src/jigsaw/common/core/data/array-collection.ts
- src/jigsaw/common/core/data/table-data.ts
Change-Id: I1f614cf4b5b3e2f7b53f7960bab4cd72fa66a7b6
> [新增] 自定义分页数组和表格数据，关联@7366

- src/app/app.interceptor.ts
- src/app/demo/pc/pagination/big-data/demo.component.html
- src/app/demo/pc/pagination/big-data/demo.component.ts
- src/app/demo/pc/pagination/big-data/demo.module.ts
- src/app/demo/pc/pagination/demo-set.module.ts
- src/jigsaw/pc-components/pagination/page.scss
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.ts
Change-Id: Ic613ee21d7fb30b684e40ddc35259458fec37bdd
> [优化] 优化分页组件性能以适应万以上分页的场景，关联@7364

- src/app/app.interceptor.ts
- src/app/demo/pc/pagination/big-data/demo.component.html
- src/app/demo/pc/pagination/big-data/demo.component.ts
- src/app/demo/pc/pagination/big-data/demo.module.ts
- src/app/demo/pc/pagination/demo-set.module.ts
- src/jigsaw/pc-components/pagination/pagination-item.scss
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.ts
Change-Id: I32207f11cef973137c9ed71563c224285f94c9a4
> [优化] 优化分页组件性能以适应一万页以上分页的场景，关联@7364

- src/jigsaw/pc-components/input/input.scss
Change-Id: Iac6c684551a2568a84f2b4d9010760e7fd733d60
> [优化] 修改input的样式，使文字和icon上下居中

- src/app/demo/pc/pagination/big-data/demo.component.html
- src/app/demo/pc/pagination/demo-set.module.ts
Change-Id: Ie0c112701aece0073763884c4b32ab921a04c6b2
> [修复] 修复merge解决冲突时留下的保留错误

- src/jigsaw/pc-components/module.ts
Change-Id: I08a61d9c7fc193c0a43f15129c9bcabfdf249dc4
> [优化] 添加旧版的文件上传和步骤条模块

- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: Ieb8b07e2305fed63e517092a07b3
1860f9c3eaae
> [修复] 解决了drag-table里面的title没有生效的问题，解决了@7280

- src/jigsaw/pc-components/combo-select/combo-select.html
Change-Id: I6dc4b1335a6cc040077dc608ac858aeabf12fe01
> [故障] 修复select点击文字无法触发下拉,关联@7356

- src/app/demo/pc/select/select-collapse/demo.component.ts
- src/app/demo/pc/select/select-group/demo.component.ts
- src/jigsaw/pc-components/select/select-group.html
- src/jigsaw/pc-components/select/select.html
Change-Id: I24455ae4d5f63a9bc369debbcc5cf878e18accfd
> [优化] select下拉文字过长时需要提示，关联@7272

- src/jigsaw/pc-components/combo-select/combo-select.ts
Change-Id: I110c2df8924caba74000838524eedb809b1b6ac9
> [故障] 修复多选时combo高度变化，下拉不能及时更新位置，关联@7283

- src/jigsaw/common/components/loading/loading-circle.scss
Change-Id: I334c365b07537445ebf0744af12428537161a0c1
> [故障] 修复circle-loading在app的onInit里面弹出会位置不正确，关联@7353

- src/jigsaw/pc-components/list-and-tile/list-lite.ts
Change-Id: I449641277607fb81504288eeb72df31c7d29e1be
> [故障] 修复list-lite搜索时会闪动，列表更新不及时的问题，解决了@7278

- src/jigsaw/pc-components/steps/step.html
- src/jigsaw/pc-components/steps/step.scss
- src/jigsaw/pc-components/steps/step.ts
Change-Id: Ie11dee23aaf44c7f7b7fa3b88dbce18a206c9df0
> [修复] 解决拖入新版的steps显示异常的问题，解决了@7249

- src/jigsaw/common/directive/fallback/upload/upload.directive.ts
- src/jigsaw/pc-components/fallback/upload/upload.scss
Change-Id: I224323927f28ada88d60961a7dada6966b1d75ca
> [故障] 修复旧的上传文件组件样式问题，关联@7251

- src/app/demo/pc/select/searchable/demo.component.ts
- src/jigsaw/pc-components/select/index.ts
- src/jigsaw/pc-components/select/select-base.ts
- src/jigsaw/pc-components/select/select.html
Change-Id: Ie869033cfd7d5d8207e015daa6b1478c15f100b9
> [新增] 新版的下拉框组件增加搜索功能，关联@7354，@7328

- src/jigsaw/pc-components/pagination/pagination.html
> [故障]分页组件的pageSize无法国际化的问题，关联@7241

- src/jigsaw/pc-components/date-and-time/time-picker.scss
Change-Id: I49420f9c4f585ee085b1895dd5b23877cf9a35f6
> [故障] 修复时间组件点击向上箭头时分秒的数字会减少，解决了@7310

- src/jigsaw/pc-components/transfer/transfer-list.html
- src/jigsaw/pc-components/transfer/transfer.scss
Change-Id: I4f94c5273585ab7f8bfbc418be08e25c05a55f1f
> [修复] 解决了transfer组件分页部分高度问题，解决了@7292

- src/app/demo/pc/table/switch-renderer/demo.component.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I41e0691123f0df98ecb2883189458e1ebc21e1aa
> [故障] 修复动态修改表格开关组件渲染器的readonly属性不能立即生效，解决了@7320

- src/jigsaw/pc-components/combo-select/combo-select.ts
- src/jigsaw/pc-components/select/select-base.ts
Change-Id: I1ef2c1cb6f99f19b8e69a2c186c50e8449a45327
> [故障] combo组件和select组件无法显示表单初始值,解决了@7319

- src/app/demo/pc/collapse/basic/demo.component.html
- src/app/demo/pc/collapse/basic/demo.component.ts
- src/app/demo/pc/collapse/basic/demo.module.ts
- src/jigsaw/pc-components/collapse/collapse-pane.html
- src/jigsaw/pc-components/collapse/collapse.scss
- src/jigsaw/pc-components/collapse/collapse.ts
- src/jigsaw/pc-components/select/select-group.html
- src/jigsaw/pc-components/upload/upload-result.html
- src/jigsaw/pc-components/upload/upload-result.scss
Change-Id: I44be4a0dd35b35eacfeafa2f6387d52e96177e30
> [修复] 解决了折叠框分不清标题和内容，解决了@7313

- src/app/demo/pc/combo-select/set-width/demo.component.css
Change-Id: I9d3a1eeb710c99a889d2d3d02458b99e6cf80852
> [优化] 优化demo combo-select/set-width的输入框布局，解决了@7311

- src/jigsaw/pc-components/collapse/collapse-pane.html
- src/jigsaw/pc-components/collapse/collapse.scss
- src/jigsaw/pc-components/collapse/collapse.ts
Change-Id: I8834563e25885741818b32c9ef050dab7e9f5bc0
> [修复] 解决collapse输入arrowPosition属性无效的问题，关联@7235

- src/jigsaw/pc-components/menu/menu.ts
Change-Id: I0776095162f22e03df1f50677de8a055c84dcb7c
> [故障] 菜单列表鼠标悬停右边的箭头会移动，解决了@7276

- src/jigsaw/pc-components/tag/tag.scss
Change-Id: I5e6bd51f96ba95062501307688b6aef0203ffeb8
> [优化] 优化tag组件disabled状态下鼠标表现，解决了@7231

- src/app/demo/pc/menu/in-dialog/demo.component.html
- src/app/demo/pc/menu/in-dialog/demo.module.ts
Change-Id: I58001c7469540c0c942d6ce73e836c361aac18c8
> [优化] /menu/in-dialog 的demo中,左侧菜单打开后,不出现滚动条，解决了@7225

- src/jigsaw/pc-components/tag/tag.html
- src/jigsaw/pc-components/tag/tag.scss
- src/jigsaw/pc-components/tag/tag.ts
1.Tag的添加模式，只有在点击中间的加号才有用的问题；
2.同时设置 isAdd和closable时，图标位置歪了；
3.disabled之后，仍然可以删除
> [优化] 优化Tag若干问题，关联@7227

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
Change-Id: I374b306180ec51a65246dc5a6e8bd48982de7950
> 【修复】解决颜色色值在用HSL色时和HEX色值不匹配问题，解决了@7206

- src/jigsaw/pc-components/select/select-base.ts
- src/jigsaw/pc-components/select/select-group.html
- src/jigsaw/pc-components/select/select.html
Change-Id: Ic5e77d992b6217d103bdeb1911ca5e5f3f964fcf
> [故障] 修复下拉多选带搜索时复选框全选不自动更新状态，解决了@7217

- src/app/demo/pc/date-time-picker/confirm-button/demo.component.html
- src/app/demo/pc/date-time-picker/confirm-button/demo.component.ts
- src/app/demo/pc/date-time-picker/confirm-button/demo.module.ts
- src/app/demo/pc/date-time-picker/limit/demo.component.html
- src/app/demo/pc/date-time-picker/limit/demo.component.ts
- src/app/demo/pc/date-time-picker/limit/demo.module.ts
- src/jigsaw/pc-components/date-and-time/date-picker.ts
- src/jigsaw/pc-components/date-and-time/date-time-picker.html
- src/jigsaw/pc-components/date-and-time/date-time-picker.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-picker.html
- src/jigsaw/pc-components/date-and-time/range-date-time-picker.ts
- src/jigsaw/pc-components/date-and-time/time-picker.ts
> [故障] 时间选择组件在设置了showConfirmButton属性时，非时分秒粒度下无法正常更新，以及动态改变limit时无法自动修正合法值的问题，关联@7219

- src/jigsaw/pc-components/steps/step.ts
> [故障] 修复Steps组件在未配置current属性时，动态切换current无效的问题

- src/jigsaw/pc-components/steps/numeric-steps/numeric-steps.ts
> [故障] 修复数字步骤条在未配置current属性时，动态切换current无效的问题

- src/jigsaw/pc-components/input/input.html
- src/jigsaw/pc-components/input/input.scss
- src/jigsaw/pc-components/input/search-input.scss
Change-Id: I52f98b36cc77c32a08f22e1ae8c89df3c3c4f645
> [优化] 优化了input清除按钮；优化了search-input的placeholder在disabled状态下的颜色；解决了@7196

- src/jigsaw/pc-components/select/select-group.html
- src/jigsaw/pc-components/upload/upload-result.html
Change-Id: I281662ef099fae836b70a952bd25d8b8b38f3911
> [修复] 解决select-collapse折叠箭头在左侧的问题，解决了@7162

- src/jigsaw/pc-components/list-and-tile/button-bar.scss
- src/jigsaw/pc-components/list-and-tile/button-bar.ts
Change-Id: If5602e4e14d4ab3ecfc88a2a4b4f23792c45ef29
> [修复] 解决button-bar文字不居中的问题，解决了@7105

- src/app/demo/pc/switch/size/demo.component.html
- src/jigsaw/pc-components/switch/switch.html
- src/jigsaw/pc-components/switch/switch.scss
Change-Id: I8a343983c9039d6db6dcf25061cee79a0dfa7940
> [修复] switch增加溢出隐藏，解决了文字超出问题，解决了@7078

- src/app/demo/pc/button-bar/basic/demo.component.ts
Change-Id: I1e41deb3b2e397d7806a8c79dccdc90f2f0c5298
> [优化] 优化button-bar的demo中图标相似的问题，解决了@7103

- src/jigsaw/common/core/theming/theme.ts
- src/jigsaw/pc-components/date-and-time/time-picker.scss
Change-Id: I4444c78c10fe584737ec707a26725d130492bf82
> [故障] 深色皮肤下弹出深色背景与组件背景不一致，解决了@7064,@7057，@7067

- src/app/demo/pc/button/preset/demo.component.html
Change-Id: I688ae4dcae3a53ad73552b20e8095797ccc5e353
> [优化] 优化button/preset demo的标题，解决了@7111

- src/app/demo/pc/loading/dom-inner/demo.component.html
Change-Id: Id712837901b62ae32f18bbfff4a16c9537c6460d
> [优化] 优化loading/dom-inner demo，解决了@7054

- .travis.yml
- src/jigsaw/pc-components/input/auto-complete-input.scss
Change-Id: If20e2b8952517e4d500616df61d4da8d54a377ae
> [故障] 修复auto-complete-input在深色皮肤下显示问题，解决了@7072

- src/jigsaw/pc-components/steps/step.scss
Change-Id: I19528cbe79d0481510ae965eeb03de0aa4b9498a
> [修复] 修复了step组件纵向步骤条颜色不对的问题，解决了@7167

- src/jigsaw/pc-components/checkbox/checkbox.ts
Change-Id: If6517583cc71a8cd99b2955cfa157e5e2c7b8098
http://localhost:4200/#/pc/checkbox/basic
> [优化] 优化了checkbox关掉中间状态时，中间状态不改变的问题，解决了@7109

- src/jigsaw/common/directive/menu/cascading-menu.ts
- src/jigsaw/pc-components/menu/menu.scss
- src/jigsaw/pc-components/menu/menu.ts
Change-Id: I1ef367b55a01e18a97e293a5988b952d257ab959
> [故障] 修复menu在dark皮肤下的显示问题，解决了@7061

- src/app/demo/pc/float/overlapping/demo.component.html
- src/jigsaw/pc-components/menu/menu.ts
Change-Id: I01b4630a0542706b9bc7aed5bcf089965c8bdd95
> [故障] 修复menu默认皮肤下样式问题，float/overlapping demo优化，解决了@7065

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
Change-Id: Ifc9e215ff28cce4518158859da233b2ab57f5a20
> [故障] 修复抽屉在dark皮肤下没有边界，解决了@7066

- src/app/demo/pc/list-lite/searchable/demo.component.html
- src/app/demo/pc/list-lite/searchable/demo.module.ts
- src/app/demo/pc/loading/font-icon/demo.component.html
- src/app/demo/pc/loading/user-defined/demo.component.html
- src/app/demo/pc/loading/user-defined/demo.module.ts
- src/app/demo/pc/pagination/big-data/demo.component.html
- src/app/demo/pc/pagination/big-data/demo.module.ts
- src/app/demo/pc/pagination/size/demo.component.html
- src/app/demo/pc/pagination/size/demo.module.ts
- src/app/demo/pc/select/searchable/demo.component.html
- src/app/demo/pc/select/searchable/demo.module.ts
- src/app/demo/pc/slider/update/demo.component.html
- src/app/demo/pc/slider/update/demo.module.ts
- src/app/demo/pc/table/checkbox-column-pageable/demo.component.html
- src/app/demo/pc/table/checkbox-column-pageable/demo.module.ts
- src/app/demo/pc/table/checkbox-column/demo.component.html
- src/app/demo/pc/table/checkbox-column/demo.module.ts
- src/app/demo/pc/table/rebuild-table-data/demo.component.html
- src/app/demo/pc/table/rebuild-table-data/demo.module.ts
- src/app/demo/pc/tooltip/moving-tooltip/demo.component.html
- src/app/demo/pc/tooltip/moving-tooltip/demo.module.ts
Change-Id: I9cfa0556b66b0545af885c3ffbcaf78403c0c59f
> [优化] 修改部分demo以适配暗色皮肤，解决了@7055

- src/jigsaw/pc-components/radio/radio.scss
Change-Id: Icaa13ef2cc14dda406d0f4f7fdcadf70d3957977
> [故障] radio在dark皮肤下会有背景色，解决了@7129

- src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I051b8761e0f6fae005278981a80c608207cab346
> [修复] 解决了menu/nav-inline 点击菜单不变色的问题，解决了@7087

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: I2c82c9f49f8f5713b2ab5a71766ebb8d8249954f
> [故障] 修复tab页签在dark皮肤下的显示问题，解决了@7119

- src/jigsaw/pc-components/combo-select/combo-select.scss
Change-Id: I567b70dadf838f7139f3b6dbfb025d031e92dc72
> [优化] 去掉combo搜索框的边框，解决了@7101，@7102，@7108

- src/jigsaw/common/directive/movable/movable.ts
Change-Id: I9dea3bcb9937169bd59ff49b5386f1eb9a44d934
> [故障] dialog设置底部弹出后，移动过程中会拉长自身高度，解决了@7098

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/pc-components/switch/switch.scss
- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: Ic09c47da23ac7f35962cfd642f61d2204de4d754
> [修复] 修改了dark模式组件背景参数，修改了tab及switch的黑暗模式显示效果，解决了@7052，@7119

- src/app/demo/pc/drag-drop/simple-table-dragdrop/table-renderer.ts
Change-Id: Ib7d0f1f091229e01a29bf3a1010ab2c868abee1f
> [故障] 修复drag-drop/simple-table-dragdrop table背景变白，解决了@7126

- src/jigsaw/pc-components/button/button.scss
Change-Id: I73974f2dad77d6312a2c3cb7fb582eb3bc23eac0
> [优化] 去掉按钮默认行高配置，采用flex居中，解决了@7031

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
Change-Id: I918dc1d62f6f23c410932faf4690a2ca9e4f4301
> [优化] 对齐button组件在dark模式下的颜色，解决了@7059

- src/app/demo/pc/select/multiple/demo.component.html
Change-Id: Ifa4549a358099d0f0e251c2316f1e7377f22da3a
> [优化] 优化demo select/multiple选择最大宽度，解决了@7082

- src/jigsaw/pc-components/button/button.scss
- src/jigsaw/pc-components/checkbox/checkbox.scss
Change-Id: Iea11101a03ae55967512124b2ba950eb5df7176b
> [优化] 优化checkbox/disabled状态的背景色，解决了@7058

- src/app/demo/pc/trusted-html/full/demo.component.css
- src/app/demo/pc/trusted-html/full/demo.component.html
- src/app/demo/pc/trusted-html/full/demo.component.ts
- src/app/demo/pc/trusted-html/full/demo.module.ts
Change-Id: Ic09fad7d0dedb4ba7c7cc30df5d775c7abb6ef87
> [优化] trusted-html/full 输入框使用jigsaw-textarea，解决了@7047

- src/app/demo/pc/time-section/fill-back/demo.component.ts
Change-Id: I050f3548fab8f9348ac1ca23b3dac7adf7883513
> [优化] 优化time-section/fill-back demo填充问题，解决了7096

- src/app/demo/pc/cascade/with-combo/demo.component.html
Change-Id: I5e860be4a6ee49e5173bb5bf28b97ffbcb0c4530
> [故障] 修复cascade/with-combo 下拉高度变化时容易自动关闭下拉，解决了@7110

- src/app/demo/pc/combo-select/events/demo.component.css
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/tag/tag.scss
Change-Id: If407412f383b3f5d87d1fd69f0a2c3967f3e2068
> [修复] 修复Combo里面的tag位置，解决了@7183，@7035

- src/app/demo/pc/fish-bone/full/demo.component.ts
- src/jigsaw/pc-components/fish-bone/fish-bone-item.scss
- src/jigsaw/pc-components/fish-bone/fish-bone.scss
Change-Id: I74333004d83d6d34b88ac5d7a377a2f67a54b760
> [优化] 优化鱼骨图在亮色和暗色皮肤下的显示，解决了@7094

- src/jigsaw/pc-components/select/select-base.ts
Change-Id: I03b7da0c73e3250b65b5dfe9d8e07cd9f49cb06c
> [优化] 对select值做空值保护 ，解决了@7036

- src/jigsaw/common/directive/float/float.ts
- src/jigsaw/pc-components/button/button.scss
- src/jigsaw/pc-components/checkbox/checkbox.scss
Change-Id: I40821665bdd6c7f5ca6558c9f9e24002db4d0428
> [故障] 修复浮动指令设置负的垂直偏移三角箭头的位置不准确，解决了@7086,@7027

- src/app/demo/pc/slider/update/demo.component.ts
- src/jigsaw/pc-components/slider/slider.ts
Change-Id: I4878b81c2b27f3f8d4c64dada3dcb2c319a29f01
> [故障] 修复slider更新多个值时会把位置计算错误，解决了@7166

- src/app/demo/pc/graph/resize/demo.component.ts
Change-Id: I36fb57f6d02508aa03c30854a013175fb9bdcc50
> [故障] 修复graph/resize demo修改某一个值的时候graph不会刷新，解决了@7070，@7089

- src/app/demo/pc/i18n/full/demo.component.html
- src/app/demo/pc/i18n/full/demo.component.ts
- src/app/demo/pc/i18n/full/demo.module.ts
- src/jigsaw/pc-components/tabs/index.ts
- src/jigsaw/pc-components/tabs/tab-bar.html
- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: I1e0cc5433e40049ae74f9c856934826f906fc9b2
添加到下拉里面了
> [故障] 修复tab编辑状态下的添加按钮在溢出时会被隐藏掉，解决了@7076

- src/jigsaw/common/core/data/graph-data.ts
Change-Id: If7be757de03c36fbe855edf4df01b97f8d671f6a
> [故障] 修复环形比例图显示不正确，解决了@7085

- src/app/demo/pc/graph/basic/demo.component.ts
- src/app/demo/pc/graph/download-directive/demo.component.ts
- src/app/demo/pc/graph/formatter/demo.component.ts
Change-Id: I760e5dbdbd79631ff9f26ce97487b2c3100e0422
> [优化] graph demo标题与图例重合的问题，解决了@7093，@7090

- src/app/demo/pc/float/pos-reviser/demo.component.css
- src/app/demo/pc/float/pos-reviser/demo.component.html
- src/app/demo/pc/float/pos-reviser/demo.component.ts
Change-Id: Ibcebd695bb3309f15db68bfc43256486b88108e9
因为用了原生的div，颜色是固定的
> [优化] 优化了float/pos-reviser demo在深色背景下的显示问题，解决了@7025

- src/app/demo/pc/badge/move/demo.component.css
- src/app/demo/pc/badge/move/demo.component.html
- src/app/demo/pc/movable/demo-set.module.ts
- src/app/demo/pc/movable/move-and-click/demo.component.css
- src/app/demo/pc/movable/move-and-click/demo.component.html
- src/app/demo/pc/movable/move-and-click/demo.component.ts
- src/jigsaw/common/directive/movable/movable.ts
- src/jigsaw/pc-components/alert/alert.html
- src/jigsaw/pc-components/dialog/dialog.html
Change-Id: Ib003cead889e5e33d2a3efa73ce23bc82440af82
> [新增] 增加移动指令的定位类型和偏移的配置，关联@7020

- src/jigsaw/common/core/data/array-collection.ts
- src/jigsaw/pc-components/select/select-base.ts
Change-Id: If9b831e5e72b1eb35cb7f22a6041fb6fa78e1a26
> [修复] 解决了select过滤时，searchable属性无效的问题，解决了@7043

- src/jigsaw/pc-components/box/box.ts
Change-Id: I364fa865531b9debdcf034fd26cec8e10ffdc06a
> [故障] 修复box组件在拖动改变尺寸的时候，会出现原始滚动条，解决了@7009

- src/app/demo/pc/box/demo-set.module.ts
- src/app/demo/pc/box/performance/demo.component.css
- src/app/demo/pc/box/performance/demo.component.html
- src/app/demo/pc/box/performance/demo.component.ts
- src/app/demo/pc/box/performance/demo.module.ts
- src/jigsaw/pc-components/box/box.ts
Change-Id: I1689839a407bec6256adcec82ceb1af4dea18c82
> [优化] 消除box的callLater异步处理，优化box的性能，增加box性能测试demo

- src/app/demo/pc/combo-select/trigger/demo.component.html
- src/app/demo/pc/combo-select/trigger/demo.component.ts
Change-Id: Ifd0bcf00e7187b1e2182712b49e219e8e49c9b20
> [故障] 修复combo/trigger demo 连续点击open按钮会切换下拉打开关闭，解决了@7107

- src/jigsaw/pc-components/radio/radio.scss
> [修复] 对齐radio组件规范，解决了@6999

- src/app/demo/pc/theme/build-in/demo.component.css
- src/app/demo/pc/theme/build-in/demo.component.html
- src/app/demo/pc/theme/build-in/demo.component.ts
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-light.scss
- src/jigsaw/pc-components/button/button.scss
- src/jigsaw/pc-components/cascade/cascade.scss
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/date-and-time/date-picker.scss
- src/jigsaw/pc-components/date-and-time/time-picker.scss
- src/jigsaw/pc-components/date-and-time/time-pop.scss
- src/jigsaw/pc-components/date-and-time/time-section.scss
- src/jigsaw/pc-components/input/auto-complete-input.scss
- src/jigsaw/pc-components/input/input.scss
- src/jigsaw/pc-components/input/numeric-input.scss
- src/jigsaw/pc-components/input/prefix-suffix-widget.scss
- src/jigsaw/pc-components/list-and-tile/list-option.scss
- src/jigsaw/pc-components/menu/navigation-menu.scss
- src/jigsaw/pc-components/menu/navigation-menu.ts
- src/jigsaw/pc-components/select/select.scss
- src/jigsaw/pc-components/switch/switch.scss
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/tabs/tab.scss
- src/jigsaw/pc-components/textarea/textarea.scss
- src/jigsaw/pc-components/tree/tree.scss
Change-Id: I116def4d89957a521e6daab90e10a3e3db23598a
> [新增] navigation组件内部实现多个主题；对齐list黑暗模式规范；解决了@6998

- src/app/demo/pc/tab/with-ngfor/demo.component.html
- src/app/demo/pc/tab/with-ngfor/demo.component.ts
- src/app/demo/pc/tab/with-ngfor/demo.module.ts
- src/jigsaw/pc-components/tabs/tab.ts
Change-Id: Id4e9cb53913745566313182d9e838899e7d7f32c
> [故障] 修改无头tab里的pane使用ngFor时无法检测到数据的变化，关联@6997

- src/jigsaw/pc-components/upload/upload-result.html
- src/jigsaw/pc-components/upload/upload-result.ts
Change-Id: Ia96d83c4c5c3a1695a569b2a52a33fdbf12d9541
> [故障] 修复文件上传显示组件在折叠起来后，鼠标hover上去时，有意外的滚动条，关联@7010

- src/app/demo/pc/table/sudoku/demo.component.html
- src/app/demo/pc/table/sudoku/number-renderer.ts
Change-Id: Ie1a0002b6bad2a4863da91f6b877b1ef4be6f8ce
> [修复] 修复了table/sudoku刷新时会出现少一行的情况，解决了@7050

- src/jigsaw/pc-components/slider/slider-handle.html
- src/jigsaw/pc-components/slider/slider.ts
Change-Id: Iae872acbd6ba961f9e80c6444cf56a83cda549d0
> [故障] 修复slider数值比较长时会换行并挡住滑动按钮，解决了@7023

- src/app/switch-demo.component.ts
- src/jigsaw/common/assets/scss/reset.scss
Change-Id: Icf02737b181ef9ae16e2f5487ec488cdd26f83af
> [优化] 优化深色系下jigsaw demo首页的图标，解决了@7012

- src/jigsaw/pc-components/input/auto-complete-input.ts
Change-Id: I69e997dcec4e05fd54a44c661f8fd9252601ce6a
> [修复] 解决了组件搜索在过滤时会出现空白，解决了@7113

- src/app/demo/pc/slider/handling-multi-value/demo.component.html
- src/app/demo/pc/steps/basic/demo.component.html
- src/app/demo/pc/steps/context/demo.component.html
- src/app/demo/pc/steps/demo-set.module.ts
- src/app/demo/pc/steps/events/demo.component.html
- src/app/demo/pc/steps/goto-step/demo.component.html
- src/app/demo/pc/steps/many-steps/demo.component.css
- src/app/demo/pc/steps/many-steps/demo.component.html
- src/app/demo/pc/steps/many-steps/demo.component.ts
- src/app/demo/pc/steps/many-steps/demo.module.ts
- src/app/demo/pc/steps/over-length/demo.component.html
- src/jigsaw/pc-components/steps/step.html
- src/jigsaw/pc-components/steps/step.scss
> [优化]步骤条每个节点增加最小宽度，解决当步骤数较多时，显示异常的问题，解决了@6966

- src/app/demo/pc/table/big-column/demo.component.html
- src/app/demo/pc/table/big-row/demo.component.html
- src/app/demo/pc/table/big-table/demo.component.html
- src/app/demo/pc/table/checkbox-column-object-cell/demo.component.html
- src/app/demo/pc/table/renderer/demo.component.html
Change-Id: Ic18c12fc94439ed8fccfd88d3143dc4698af4d86
> [优化] 去掉table demo里不必要的trackRowBy的配置，防止用户误拷贝

- src/jigsaw/pc-components/upload/upload-result.html
- src/jigsaw/pc-components/upload/upload-result.ts
Change-Id: Ic4b42387
0b7ad99885710f3f32097ad5c6475718
> [优化] upload组件点击重新上传后，立即清空的进度条，解决了@6957

- src/jigsaw/common/assets/scss/reset.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-light.scss
Change-Id: Ic039cc11dc111d2a48f64c6fd0f0ba1335d12573
> [优化] 优化黑暗模式下滚动条的颜色，解决了@6960

- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: Iaef714522fe01d32848c2061858e132eb107e0cc
> [修复] 修改tab page模式底部border的实现方式，解决了@6931

- src/app/demo/pc/table/auto-fill-up/demo.component.css
- src/app/demo/pc/table/auto-fill-up/demo.component.html
- src/app/demo/pc/table/auto-fill-up/demo.component.ts
- src/app/demo/pc/table/auto-fill-up/demo.module.ts
- src/app/demo/pc/table/demo-set.module.ts
- src/jigsaw/pc-components/table/table.html
- src/jigsaw/pc-components/table/table.ts
http://localhost:4200/#/pc/table/auto-fill-up
> [新增] 表格组件在记录数过少，未能填满表格高度时，添加空白行，解决了@6964

- src/ngx-formly/jigsaw/form-field/src/form-field.wrapper.ts
> [故障] 表单模块中，行内组中的组件校验信息显示之后，组件对齐问题，关联了@6901

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/breadcrumb/breadcrumb.scss
Change-Id: I9343b93f5d0223554177b11f7fc8d408c0c9c8a6
> [优化] Breadcrumb组件对齐ux规范，优化了内页模式下文字hover效果，并新增导航色变量，解决了@6893

- src/app/demo/pc/upload/basic/demo.component.css
- src/app/demo/pc/upload/basic/demo.component.html
- src/app/demo/pc/upload/basic/demo.component.ts
Change-Id: Ie55d6f5cbb5733a6f28be18ec63d02c2c8987337
> [优化] upload组件demo页面优化，便于区分符合规范的功能和拓展功能，解决了@6883

- src/jigsaw/pc-components/table/table.ts
Change-Id: I2e95c0e3ab7c0b3f8544d85a1597adedd3ff7c52
> [新增] table增加additionalData重置的方法，解决了@6848

- src/app/demo/pc/notification/full/demo.component.html
- src/app/demo/pc/notification/full/demo.component.ts
- src/jigsaw/pc-components/notification/notification.html
- src/jigsaw/pc-components/notification/notification.scss
- src/jigsaw/pc-components/notification/notification.ts
Change-Id: Idc166959dcc50c0b158ec6d2ab2bffcc515a615f
增加了500px的最大高度限制
> [优化] Notification增加最大高度限制，解决@6871

- src/app/demo/pc/upload/toggle-auto-upload/demo.component.html
- src/app/demo/pc/upload/toggle-auto-upload/demo.component.ts
- src/jigsaw/common/directive/upload/upload.directive.ts
Change-Id: Ifd39fd1bb498a105b2905628400bd785d453034b
> [故障] 解决了上传指令在同时设置[uploadImmediately]="false"和[uploadMultiple]="false"时，无法执行手动上传的问题，解决了@6857

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/radio/radio.scss
Change-Id: I9b8cba999225e2ef07d54a13ab0306b9f6b8453e
> [优化] radio组件在禁用状态颜色对齐规范，解决了@6849

- src/app/demo-description/demo-description.ts
Change-Id: Iab72bab231c1afa25d08d03534f3cba12050876f
> [故障] 修复点击查看源码控制台报错，且无法跳转到查看源码页面

- src/app/demo/pc/tooltip/demo-set.module.ts
- src/app/demo/pc/tooltip/theme/demo.component.html
- src/app/demo/pc/tooltip/theme/demo.component.ts
- src/app/demo/pc/tooltip/theme/demo.module.ts
- src/jigsaw/common/directive/float/float.ts
- src/jigsaw/common/directive/tooltip/tooltip.scss
- src/jigsaw/common/directive/tooltip/tooltip.ts
- src/jigsaw/common/service/popup.service.ts
Change-Id: If8557902c5a3530bfc5e678f0ed6e8445fda68ef
> [优化] Tooltip组件对齐ux规范，增加明、暗两种主题，解决了@6881

- src/app/demo/pc/button/demo-set.module.ts
- src/app/demo/pc/button/instances/demo.component.html
- src/app/demo/pc/button/instances/demo.component.ts
- src/app/demo/pc/button/instances/demo.module.ts
- src/jigsaw/pc-components/button/button.html
- src/jigsaw/pc-components/button/button.scss
- src/jigsaw/pc-components/button/button.ts
Change-Id: Ie2f3b1a050b7fe03384f6dabb7fee49c7d2662f4
已在size=“small”情况下测试
> [优化] Button组件与规范对齐，解决了@6852，@6874

- src/app/demo/pc/menu/usage/demo.component.html
- src/jigsaw/pc-components/menu/menu.scss
- src/jigsaw/pc-components/menu/menu.ts
> [修复] 解决了Menu组件，弹出菜单内容错乱问题，解决了@6863

- src/jigsaw/pc-components/table/table.scss
Change-Id: Id40f5082f65ec20683c301f64f7d33318d94cc86
> [优化] table 无数据对齐ux规范，解决了@6827

- src/app/demo/pc/menu/navigation/demo.component.html
- src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I2551adecd9689a3d6b64a8e8757b895f77889ce8
> [优化] jigsaw-navigation组件优化demo，添加内置主题demo的链接，解决了@6825

- src/jigsaw/common/directive/tooltip/tooltip.ts
- src/jigsaw/pc-components/menu/navigation-menu.html
- src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: Ib524d99ea7869d643155b84ca3ffd38c6fed23bc
> [优化] Navigation组件tooltip增加触发范围，结局了@6892

- src/app/demo/pc/notification/basic/demo.component.ts
- src/jigsaw/pc-components/notification/notification.scss
Change-Id: I9faeac236b628900c21a7ba6d55a68fd076940b9
> [优化] Notification组件对齐规范，解决了@6879

- src/jigsaw/pc-components/upload/upload-result.html
- src/jigsaw/pc-components/upload/upload-result.scss
Change-Id: I4e1df24286c73ad0e2af1c95d2199a4808e1ed3a
> [优化] 文件上传结果组件，待上传图标与关闭按钮分开，解决了@6783

- src/jigsaw/pc-components/select/select-base.ts
> [故障]下拉框设置初始值无效的问题

- src/app/demo/pc/upload/basic/demo.component.html
- src/app/demo/pc/upload/basic/demo.component.ts
- src/jigsaw/common/directive/upload/upload.directive.ts
- src/jigsaw/pc-components/upload/upload.html
- src/jigsaw/pc-components/upload/upload.ts
Change-Id: Ib5dcd8d153edbc16fa03abf70f486d0e8af3eed6
> [优化] Upload组件提供事件

- src/app/demo/pc/tree/editable/demo.component.html
- src/app/demo/pc/tree/editable/demo.component.ts
- src/jigsaw/pc-components/tree/tree-ext.ts
- src/jigsaw/pc-components/tree/tree.scss
Change-Id: I9468f0cd6ca5667d9828b905c8a7082af8cb06f5
> [优化] Tree组件优化了编辑节点时，输入框的宽度和高度，关联@6701

- src/app/demo/pc/alert/popup/demo.component.html
- src/app/demo/pc/alert/popup/demo.component.ts
- src/jigsaw/pc-components/alert/alert.scss
Change-Id: Id5aad365f3ed47d25a477ce4b5ecba7073c24ef8
> [修复] 当出现连续数字或字母时，alert可以自动换行了，解决了@6672

- src/jigsaw/pc-components/tree/tree-ext.ts
Change-Id: I6e89ce45e895a22fa2b7203338e8d86bf9d89368
> [优化] 编辑树节点点击小铅笔后文本后自动选中

- src/jigsaw/pc-components/pagination/pagination-item.scss
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.scss
Change-Id: I2058278bcb649a1fb32e929fe91a421211a918ba
> [优化] Pagination组件对齐规范，解决了@6888

- src/jigsaw/pc-components/dialog/dialog.ts
> 补充dialog的icon属

- src/app/demo/pc/search-input/demo-set.module.ts
- src/app/demo/pc/search-input/history-storage-key/demo.component.css
- src/app/demo/pc/search-input/history-storage-key/demo.component.html
- src/app/demo/pc/search-input/history-storage-key/demo.component.ts
- src/app/demo/pc/search-input/history-storage-key/demo.module.ts
- src/jigsaw/pc-components/input/auto-complete-input.ts
- src/jigsaw/pc-components/input/input.html
- src/jigsaw/pc-components/input/input.scss
- src/jigsaw/pc-components/input/search-input.html
- src/jigsaw/pc-components/input/search-input.scss
- src/jigsaw/pc-components/input/search-input.ts
Change-Id: Ib28376eeda22186d18d949b31338a9106e38f238
> [新增] search-input新增历史记录功能，关联@6887

- src/app/app.interceptor.ts
- src/app/demo/pc/pagination/demo-set.module.ts
- src/app/demo/pc/pagination/no-data/demo.component.css
- src/app/demo/pc/pagination/no-data/demo.component.html
- src/app/demo/pc/pagination/no-data/demo.component.ts
- src/app/demo/pc/pagination/no-data/demo.module.ts
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.ts
> [修复] 解决Pagination在无数据时，出现null的问题；解决翻页按钮在disabled状态下依旧可点的问题；解决了@6656，@6647

- src/app/demo/pc/alert/popup/demo.component.css
- src/app/demo/pc/alert/popup/demo.component.html
- src/app/demo/pc/alert/popup/demo.component.ts
- src/app/demo/pc/alert/popup/demo.module.ts
- src/jigsaw/pc-components/alert/alert.scss
- src/jigsaw/pc-components/alert/alert.ts
- src/jigsaw/pc-components/alert/common-alert.html
Change-Id: I196302ebd5032afdc565d9375c16d3af489b4df3
> [修复] Alert组件内容设置最大高度和内边距；Alert组件内容可以被选中；解决了@6633，@6632

- src/app/demo/pc/tab-bar/background/demo.component.css
- src/app/demo/pc/tab-bar/background/demo.component.html
- src/app/demo/pc/tab-bar/background/demo.component.ts
- src/app/demo/pc/tab-bar/background/demo.module.ts
- src/app/demo/pc/tab-bar/demo-set.module.ts
- src/app/demo/pc/tab/background/demo.component.css
- src/app/demo/pc/tab/background/demo.component.html
- src/app/demo/pc/tab/background/demo.component.ts
- src/app/demo/pc/tab/background/demo.module.ts
- src/app/demo/pc/tab/demo-set.module.ts
- src/jigsaw/pc-components/tabs/tab-bar.html
- src/jigsaw/pc-components/tabs/tab.scss
- src/jigsaw/pc-components/tabs/tab.ts
Change-Id: I501ee75fbed28f052ce47a536a4d56380c5ccae5
> [优化] tabs组件可以通过backgroundColor属性更改背景颜色，在页签下表现更统一，解决了@6673

- src/jigsaw/pc-components/notification/notification.ts
> [故障] 修复Notification在某些场景下弹出报错问题

- src/app/demo/pc/color-select/basic/demo.component.html
- src/jigsaw/pc-components/color-select/color-select.html
- src/jigsaw/pc-components/color-select/color-select.ts
- src/jigsaw/pc-components/color-select/index.ts
Change-Id: I924f73140aa82d2068a2925a611e7a29220ac4e1
> [新增] 颜色选择器增加optionCount属性用于限制下拉高度

- src/app/demo/pc/table/column-width/demo.component.html
- src/app/demo/pc/table/column-width/demo.component.ts
- src/app/demo/pc/table/column-width/demo.module.ts
- src/app/demo/pc/table/demo-set.module.ts
- src/jigsaw/pc-components/table/table.html
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/table/table.ts
Change-Id: Icfba5fe64d219d7bac36dc6526bc6c1481d127ed
> [故障] 修复表格单元格设置宽度不生效，关联@6613

- src/app/demo/pc/table/column-width/demo.component.html
- src/app/demo/pc/table/column-width/demo.component.ts
- src/jigsaw/pc-components/table/table.ts
Change-Id: Ie6ebf3bfc6995869f7b4fce61d5b0285ec68f001
> [优化] 增加表格contentWidth配置_inner_width_时兼容以前的列宽计算

- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: I61700b4aeeca5777b6b1955c047026bf41d42339
由https://github.com/rdkmaster/jigsaw/pull/1699引入
> [修复] 修复tab中tab-content增加padding带来的破坏性

- src/jigsaw/pc-components/chart-icon/chart-icon.ts
- src/jigsaw/pc-components/select/select-base.ts
Change-Id: Iba250ad65f8a44ab43ca8e33f90c06d4a22f6f59
> [优化] chart-icon部分组件的初始值

- src/app/demo/pc/theme/wings-theme/demo.component.html
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/select/select-collapse.scss
- src/jigsaw/pc-components/select/select-group.html
- src/jigsaw/pc-components/select/select-group.scss
- src/jigsaw/pc-components/select/select.html
- src/jigsaw/pc-components/select/select.scss
Change-Id: I847de7151756dd23563e71fd6415e660cb2eda06
> [优化] 调整select组件的wings-theme 

- src/app/demo/pc/table/tree-table/demo.component.ts
- src/jigsaw/common/core/data/table-data.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I1fd9d7b40c9a7e92f49d19dd49c90e5a62af137c
> [修复] 解决了tree-table数据超过10条时，缩进不正确的问题，关联@6597

- build/scripts/create-component-wings-theme.js
- src/jigsaw/common/common.ts
Change-Id: I26157f1792c9551004ed98d5ee59a2ee068c710c
> 修改component路径为wings-theme

- src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I02c187e01d9ed5110180f5bbdca12421be2b50f9
> [优化] Navigation调整gray状态下组件颜色以对齐规范，关联@6574

- src/jigsaw/pc-components/chart-icon/chart-icon.ts
Change-Id: Ia1c602d682545ce241bc0186ad93ae3622d81b9f
> [故障] chart-icon通过直接赋值data属性方式无法更新视图

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/input/auto-complete-input.html
- src/jigsaw/pc-components/input/auto-complete-input.scss
- src/jigsaw/pc-components/input/auto-complete-input.ts
Change-Id: Ibf3fc74d9126d69a1e500371e0b1557f8479a014
> [优化] 优化了auto-complete-input组件中，float部分无数据的表现，解决了@6573

- src/jigsaw/pc-components/list-and-tile/list.scss
Change-Id: Icf416525ecc23755031bb25ce6c26353821dca33。
> [修复] 解决list组件设置disabled属性无效的问题，关联@6571

- src/jigsaw/pc-components/dialog/dialog.scss
Change-Id: I93656e1bbe976f5ab14177733a5be6510ef30f87
> [优化] dialog组件确认安全边距对齐规范，内容区域略微变宽4px，关联@6605

- build/scripts/create-component-wings-theme.js
- src/app/demo/pc/fish-bone/full/demo.component.html
- src/app/demo/pc/tab/background/demo.component.html
- src/jigsaw/pc-components/fish-bone/fish-bone-item.scss
- src/jigsaw/pc-components/fish-bone/fish-bone.html
- src/jigsaw/pc-components/fish-bone/fish-bone.scss
- src/jigsaw/pc-components/fish-bone/fish-bone.ts
Change-Id: I13f4c80466951af3ab85cd12e008379d82cfae17
> [故障] 修复fish-bone组件表现不正常的问题，并增加了wings-theme功能，解决了@6563

- src/jigsaw/pc-components/switch/switch.scss
Change-Id: Ida834a382792c1b42bed756821def207c0f5f96d
> [故障] 解决了switch组件，在host容器内沒有垂直居中的问题

- src/jigsaw/pc-components/toast/toast.scss
Change-Id: Iadb9bfee0b8b69c74cfe54278a4c54e7cd8f8391
> [优化] 优化了toast弹出来后，切换皮肤时可以切换背景色，解决了@6580

- src/jigsaw/pc-components/dialog/dialog.scss
Change-Id: I5e5a2aa8fa6b01cd3bbe0f4460f1d54c5f7c60dc
> [优化] 优化了dialog组件在动态切换主题时可更改背景，解决了@6582

- src/jigsaw/pc-components/color-select/color-select.html
- src/jigsaw/pc-components/color-select/color-select.scss
- src/jigsaw/pc-components/color-select/color-select.ts
Change-Id: I7546f9decc1d707e28876a1b1ff58f8d656edcc4
> [优化] 颜色选择器组件文本色适配黑暗模式，解决了@6583

- src/jigsaw/pc-components/select/select-base.ts
Change-Id: I41048985e77e5ce2a3ee7666d0720120664e2c33
> [故障] 修复设置下拉折叠选择框有时设置value后combo框里面不显示值的问题

- src/jigsaw/pc-components/select/select-base.ts
Change-Id: Id609a684a9d499523a9e9e7e72f4de0b80dbf30a
> [新增] 下拉框系列增加openChange下拉打开状态变化事件

- src/jigsaw/pc-components/box/editable-box.scss
Change-Id: I90f384c7ed19086a176e88d6dd080fb13797dda7
> [故障] 设置可编辑盒子事件穿透后无法拖动resizeLine改变尺寸

- src/jigsaw/common/core/theming/prebuilt/settings/masbd-reset.scss
- src/jigsaw/pc-components/menu/navigation-menu.ts
Change-Id: I5a3eb20161aecd3ab109e12fe830d75ab7b6ad41
> [故障] 解决了智坪项目awade换肤，菜单inline模式下背景色更改为图片的问题，关联了@6485

- src/app/demo/pc/combo-select/demo-set.module.ts
- src/app/demo/pc/combo-select/valid/demo.component.css
- src/app/demo/pc/combo-select/valid/demo.component.html
- src/app/demo/pc/combo-select/valid/demo.component.ts
- src/app/demo/pc/combo-select/valid/demo.module.ts
- src/app/demo/pc/select-collapse/demo-set.module.ts
- src/app/demo/pc/select-collapse/valid/demo.component.css
- src/app/demo/pc/select-collapse/valid/demo.component.html
- src/app/demo/pc/select-collapse/valid/demo.component.ts
- src/app/demo/pc/select-collapse/valid/demo.module.ts
- src/app/demo/pc/select-group/demo-set.module.ts
- src/app/demo/pc/select-group/valid/demo.component.css
- src/app/demo/pc/select-group/valid/demo.component.html
- src/app/demo/pc/select-group/valid/demo.component.ts
- src/app/demo/pc/select-group/valid/demo.module.ts
- src/app/demo/pc/select/demo-set.module.ts
- src/app/demo/pc/select/valid/demo.component.css
- src/app/demo/pc/select/valid/demo.component.html
- src/app/demo/pc/select/valid/demo.component.ts
- src/app/demo/pc/select/valid/demo.module.ts
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/select/collapse-and-group-select.ts
- src/jigsaw/pc-components/select/select.scss
- src/jigsaw/pc-components/select/select.ts
> [故障] 解决了在select中设置valid属性无效的问题，关联@6457

- src/jigsaw/pc-components/alert/alert.scss
- src/jigsaw/pc-components/alert/common-alert.html
Change-Id: Id6af0d6f96138b6f86a47748faa6658378606795
> [优化] Alert组件内容居中对齐，关联了@6448

- src/jigsaw/common/core/theming/prebuilt/settings/masbd-reset.scss
Change-Id: I3f3ab1f557528e31da6c8f7a82ddf546ad1eb702
>  [优化] 某大数据UI对齐规范，关联了@6447

- src/jigsaw/common/core/theming/prebuilt/settings/masbd-light-reset.scss
- src/jigsaw/common/core/theming/prebuilt/settings/masbd-reset.scss
- src/jigsaw/pc-components/theming/prebuilt/masbd-light.scss
Change-Id: I787dbb9376f32e01b73565be4364a774a039e593
> [优化] 某大数据修改默认背景色，关联了@6445

- src/jigsaw/pc-components/checkbox/checkbox.ts
- src/jigsaw/pc-components/table/table-renderer.ts
- src/jigsaw/pc-components/table/table.html
Change-Id: Ie397de0ceb8947163700b3745cc579e53bc2eaf6
> [优化] table组件checkbox-renderer，在操作顶部的checkbox时，不会影响已经disabled的数据，关联了@6609

- src/jigsaw/pc-components/transfer/transfer.ts
Change-Id: Id692a280e2bfdf506d96d2b94427f88706e479bc
> [优化] transfer组件的selectItems属性需要支持Array类型

- src/app/demo/pc/box/layout-interaction/demo.component.html
- src/jigsaw/pc-components/box/editable-box.scss
Change-Id: I6975713ff2a9e9563b3ddea500e25aa4b17408dd
> [优化] 去掉可编辑盒子的溢出隐藏

- src/jigsaw/pc-components/table/table.html
Change-Id: Ifdc2e3853c66a4da2093b8d1e48a5c35d0b2e774
> [优化] 表格富文本配置能显示提示文本，关联@6665

- src/ngx-formly/jigsaw/form-field/src/form-field.wrapper.ts
> [优化] 表单组件水平对齐问题，关联了@6901,@6421

- src/jigsaw/pc-components/list-and-tile/group-lite-common.ts
- src/jigsaw/pc-components/radio/radio-lite.ts
- src/jigsaw/pc-components/select/select-base.ts
> [故障] 部分组件在表单中动态设值时，无法更新表单model的问题，关联了@6425

- src/ngx-formly/jigsaw/button/src/button.type.ts
- src/ngx-formly/jigsaw/form-field/src/form-field.wrapper.ts
> [优化] 对齐表单组件的label字体样式，关联了@6428

- src/jigsaw/pc-components/input/input.scss
- src/jigsaw/pc-components/input/search-input.html
- src/jigsaw/pc-components/input/search-input.scss
> [优化] search-input组件更换放大镜图标；新增hover样式；关联@6416

- src/jigsaw/common/core/theming/prebuilt/settings/idea-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/masbd-light-reset.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/menu/navigation-menu.scss
- src/jigsaw/pc-components/theming/prebuilt/masbd-light.scss
Change-Id: I85cd31517828b4e1819d15acee0ca7792b3c355a
> [新增] 皮肤颜色变量新增一组导航色，关联了@6442

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-base.scss
- src/jigsaw/pc-components/alert/alert.scss
- src/jigsaw/pc-components/dialog/dialog.html
- src/jigsaw/pc-components/dialog/dialog.scss
- src/jigsaw/pc-components/toast/toast.scss
- src/jigsaw/pc-components/upload/upload.scss
Change-Id: I29cc9ba6498916e27a3871c96b10a92fbee888de
> [优化] 弹窗关闭按钮与规范对齐，关联@6305

- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: I0876101197874d625e5a6ed6d525f99f4ace9ee1
> [优化] Tab hover状态样式对齐规范，关联@6374

- src/app/demo/pc/table/expand/demo.component.ts
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/table/table.ts
Change-Id: I715671590b014661c639a4baf2f352d2654ec553
> [故障] 解决了table组件展开行宽度不正确的问题；解决了最后一行展开没有下边框的问题；关联6300

- src/ngx-formly/jigsaw/checkbox/src/checkbox.type.ts
- src/ngx-formly/jigsaw/radio/src/radio.type.ts
- src/ngx-formly/jigsaw/slider/src/slider.type.ts
- src/ngx-formly/jigsaw/switch/src/switch.type.ts
> [优化] 开关等部分组件在表单中横向对齐存在误差的问题，关联了@6291

- src/jigsaw/pc-components/date-and-time/time-picker.scss
Change-Id: I2bde288ac908d52416e3aacc8b9a76158081da4d
> [故障] 解决火狐浏览器在时间组件中的兼容性问题，关联了@6277

- src/app/demo/pc/menu/navigation/demo.component.html
- src/app/demo/pc/menu/navigation/demo.component.ts
- src/jigsaw/pc-components/menu/index.ts
- src/jigsaw/pc-components/menu/navigation-menu.html
- src/jigsaw/pc-components/menu/navigation-menu.ts
> [新增] navigation导航菜单增加角标，关联了@6303

- src/app/demo/pc/upload/basic/demo.component.css
- src/app/demo/pc/upload/basic/demo.component.html
- src/app/demo/pc/upload/basic/demo.component.ts
- src/jigsaw/pc-components/upload/upload.ts
Change-Id: I57585af9ed8b43753736deefdbc94269229c0cae
http://localhost:4200/#/pc/upload/basic
> [故障] 解决了upload组件在设置手动上传后，拖入文件依旧自动上传的问题；upload组件添加手动控制方法；关联了@6260

- src/app/demo/pc/upload/basic/demo.component.css
- src/app/demo/pc/upload/basic/demo.component.html
- src/app/demo/pc/upload/basic/demo.component.ts
- src/jigsaw/pc-components/upload/upload-result.ts
- src/jigsaw/pc-components/upload/upload.html
- src/jigsaw/pc-components/upload/upload.ts
http://localhost:4200/#/pc/upload/basic
> [新增] 为upload组件添加手动清除方法，关联了@6260

- src/app/demo/pc/badge/mask/demo.component.html
- src/jigsaw/common/core/theming/prebuilt/settings/idea-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/common/directive/badge/badge.scss
- src/jigsaw/common/directive/badge/badge.ts
Change-Id: I0e1eedf4e41a17337d5e9af1c75d9943df779f32
> [优化] 解决了badge功能在深色模式下的mask看不清的问题，关联@6584

- src/jigsaw/pc-components/upload/upload-result.html
- src/jigsaw/pc-components/upload/upload-result.scss
- src/jigsaw/pc-components/upload/upload.scss
Change-Id: Id63787742d818995849115a103c36b2822fb2cef
> [优化] 上传组件和上传结果组件文本优化，关联了@6247

- src/jigsaw/common/core/theming/prebuilt/settings/zjcm-reset.scss
Change-Id: I4469ae91a98d9e698305d144f1dcbed6b7c1fc64
> [故障] 解决表格底部出现横向滚动条的问题，关联@6240

- src/jigsaw/common/core/theming/prebuilt/settings/zjcm-reset.scss
- src/jigsaw/pc-components/radio/radios-lite.scss
- src/jigsaw/pc-components/radio/radios.scss
Change-Id: I1ed2d18172c78802f2ba7f831ef7ef98a66ffcfd
> [优化] 定制皮肤里radio选中选项在disable时，增加对比度，关联了@6238

- src/app/demo/pc/tag/selectable/demo.component.css
- src/app/demo/pc/tag/selectable/demo.component.html
- src/app/demo/pc/tag/selectable/demo.component.ts
- src/app/demo/pc/tag/selectable/demo.module.ts
- src/jigsaw/pc-components/combo-select/combo-select.html
- src/jigsaw/pc-components/combo-select/combo-select.ts
- src/jigsaw/pc-components/tag/tag.scss
- src/jigsaw/pc-components/tag/tag.ts
> [新增] combo-select的选中项，支持设置背景色，关联了@6322

- src/jigsaw/common/core/theming/prebuilt/settings/zjcm-reset.scss
Change-Id: I48708728dd9b28a18d50aa1043da11795789ca3f
> [优化] ZJCM定制皮肤表格边框优化，关联了@6227

- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/date-and-time/date-time-select.ts
- src/jigsaw/pc-components/date-and-time/range-date-time-select.ts
Change-Id: Ia8d72b73acdd7a185ab52e59cbcebeb0a5fb0a29
> [优化] date-time-select & range-date-time-select 默认的触发下拉事件改为点击，关联了@6188

- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I3c7558ef7e819a9ef003d90d6fa1163529b12942
> [故障] 切换显示隐藏表格checkbox渲染器无效，关联@6121

- src/app/demo/pc/table/demo-set.module.ts
- src/app/demo/pc/table/expand-pageable/demo.component.css
- src/app/demo/pc/table/expand-pageable/demo.component.html
- src/app/demo/pc/table/expand-pageable/demo.component.ts
- src/app/demo/pc/table/expand-pageable/demo.module.ts
- src/jigsaw/pc-components/table/table.ts
Change-Id: Ia20187de810ce00bbae896eb76f9c2797b1dcb25
http://localhost:4200/#/pc/table/expand-pageable
> [优化] table组件展开行，在分页数据改变当前页后，会自动关闭，关联了@6110

- src/jigsaw/pc-components/tabs/tab-bar.html
- src/jigsaw/pc-components/tabs/tab.scss
Change-Id: Ib31677442526ea07d204d225eba9f633afbfeb4e
> [优化] 页签tab对齐规范，解决了@6724

- src/app/demo/pc/novice-guide/basic/demo.component.ts
- src/jigsaw/common/novice-guide/novice-guide.ts
- src/jigsaw/common/novice-guide/types.ts
Change-Id: I7f998b2bac0dc14ac8b6ed3b0a5093d99be0df54
> [新增] 新手指南增加delay用于等待元素稳定后弹出,解决了@6014

- src/jigsaw/common/novice-guide/novice-guide.ts
- src/jigsaw/common/novice-guide/types.ts
- src/jigsaw/common/novice-guide/utils.ts
Change-Id: I97baf92f218483ec29299d97188a42cbdae036b4
> [新增] 本地存储增加新手指南的开关，关联@6018

- src/jigsaw/common/novice-guide/novice-guide.ts
- src/jigsaw/common/novice-guide/types.ts
Change-Id: I0459e2c0a3bff05b46575e5d6cb25a90ba6ff5cb
> [新增] 新手指南增加总是弹出的配置，关联了@6638

- src/jigsaw/common/core/theming/prebuilt/settings/masbd-reset.scss
- src/jigsaw/pc-components/menu/navigation-menu.scss
Change-Id: I89a7e15dbd5c34490a927ddfb42952d2fc010848
> [优化] 侧边导航一级菜单选中状态背景色加深，关联了@5996

- src/jigsaw/pc-components/upload/index.ts
Change-Id: I1893af03fefb7bd710aec76fce050b44ff0ec0fc
> [优化] upload组件国际化词条样式优化，关联了@5970

- src/app/for-internal/demo/pc/ribbon/basic/demo.component.css
- src/app/for-internal/demo/pc/ribbon/basic/demo.component.html
- src/app/for-internal/demo/pc/ribbon/basic/demo.component.ts
- src/jigsaw/common/directive/ribbon/ribbon.ts
Change-Id: I83d61680b1c53c4198ad013074034cc99cea2cb3
> [新增] Jigsaw-ribbon支持设置渐进色背景；支持设置文本颜色；关联了@5870

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-base.scss
- src/jigsaw/common/directive/badge/badge.scss
- src/jigsaw/common/directive/ribbon/ribbon.scss
- src/jigsaw/common/directive/ribbon/ribbon.ts
Change-Id: I74522d43f23278900fa7dabbf8a7d07caaf2ab7d
> [新增] Jigsaw-ribbon重新设置z-index，以确保ribbon出现在正确的层级；关联了@5867

- src/app/for-internal/demo/pc/novice-guide/basic/demo.component.css
- src/app/for-internal/demo/pc/novice-guide/basic/demo.component.html
- src/app/for-internal/demo/pc/novice-guide/basic/demo.component.ts
- src/jigsaw/common/novice-guide/novice-guide.ts
- src/jigsaw/common/novice-guide/types.ts
- src/jigsaw/common/novice-guide/utils.ts
Change-Id: I6d33b884c15a08673ede180d929299d0e3ff735d
> [故障] 修复新手指引组件会同时存在多个指引的问题；优化分步指引的校验逻辑；解决了@5820

- src/app/for-internal/demo/pc/table/content-width/demo.component.html
- src/app/for-internal/demo/pc/table/content-width/demo.component.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/table/table.ts
Change-Id: I247d2799d927aa7b49fd82f42fcacec9355af12e
> [故障] 修复表格在设置contentWidth后，通过表头撑开表格宽度有误的问题，关联@5805

- src/jigsaw/pc-components/table/table.html
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/table/table.ts
Change-Id: Id77313b7e10a69749a37782286684c0d283039ec
> [故障] 解决火狐下table设置contentWidth无效的问题，解决了@5787

- src/app/for-internal/demo/pc/tooltip/scenes/demo.component.html
- src/app/for-internal/demo/pc/tooltip/scenes/demo.component.ts
- src/app/for-internal/demo/pc/tooltip/scenes/demo.module.ts
> [优化] Tooltip Demo新增对话框场景，解决了@5706

- src/jigsaw/common/core/data/table-data.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
http://localhost:4200/#/pc/table/header-filter
> [故障] 解决列头过滤和搜索相结合时有意外条目的问题，解决了@5651

- src/jigsaw/pc-components/select/select-base.ts
Change-Id: I0a17b4effe3bcb08f40971efb60bc9c2ee83c1db
> [故障] 修复下拉组件手动设置disabled不生效，关联@5648

- src/app/for-internal/demo/pc/table/header-filter/demo.component.ts
- src/app/libs/app.interceptor.ts
- src/jigsaw/common/core/data/table-data.ts
http://localhost:4200/#/pc/table/header-filter
> [故障] 解决表格自定义服务端分页时，发出去的参数数据结构发生变化的问题，解决了@5649

- src/app/for-internal/demo/pc/menu/navigation/demo.component.ts
- src/jigsaw/common/directive/tooltip/tooltip.ts
- src/jigsaw/pc-components/menu/navigation-menu.html
- src/jigsaw/pc-components/menu/navigation-menu.scss
> [故障] 解决导航菜单在词条比较长的时候，界面异常的问题，解决了@5588

- src/jigsaw/pc-components/checkbox/checkbox.scss
- src/jigsaw/pc-components/combo-select/combo-select.scss
- src/jigsaw/pc-components/input/numeric-input.scss
- src/jigsaw/pc-components/tag/tag.scss
> [优化] 支持组件disabled后可以选中文本，解决了@5553

- src/app/for-internal/demo/pc/table/align-content/demo.component.html
- src/app/for-internal/demo/pc/table/align-content/demo.component.ts
- src/app/for-internal/demo/pc/table/align-content/demo.module.ts
- src/jigsaw/pc-components/table/table.scss
http://localhost:4200/#/pc/table/align-content
> [故障] TreeTable换行文本左对齐，关联了@5511

- src/app/for-external/app.module.ts
- src/app/for-external/demo/translate/demo.component.html
- src/app/for-external/demo/translate/demo.component.ts
- src/app/for-external/demo/translate/demo.module.ts
- src/app/for-external/demo/translate/readme.md
- src/app/for-external/router-config.ts
> [新增] IDEA网站添加如何切换国际化的示例，解决了@5476

- src/app/for-internal/demo/pc/pagination/basic/demo.component.html
- src/app/for-internal/demo/pc/pagination/basic/demo.component.ts
- src/app/for-internal/demo/pc/pagination/basic/demo.module.ts
- src/jigsaw/pc-components/pagination/pagination.html
- src/jigsaw/pc-components/pagination/pagination.ts
> [优化] pagination组件页数下拉框的宽度可自适应一万以内的条数所需宽度，关联了@5418

- src/jigsaw/pc-components/process-status/process-status-multiline.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I15afb7aa348a6c48a0a853b60212c5c1cf451b93
> [故障] 修复升级谷歌浏览器到109版本event.path被弃用的问题

- src/jigsaw/pc-components/box/editable-box.ts
Change-Id: Ica61dbeccfd0b22437237048325f49ae0f21fafa
> [故障] 修复固定尺寸的可编辑盒子在同级盒子改变尺寸时会跳动减少尺寸，关联@5413

- src/app/for-internal/demo/pc/tree/size/demo.component.ts
- src/jigsaw/pc-components/tree/tree.scss
> [优化] Tree组件对齐规范，关联了@6926

- src/jigsaw/pc-components/menu/index.ts
> [优化] Navigation组件内置国际化对齐规范，解决了@5361

- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
- src/jigsaw/pc-components/menu/navigation-menu.scss
> [优化] navigation-menu优化收起按钮hover色，解决了@5357

- src/app/for-internal/demo/pc/tree/size/demo.component.html
- src/app/for-internal/demo/pc/tree/size/demo.component.ts
- src/app/for-internal/demo/pc/tree/size/demo.module.ts
- src/jigsaw/pc-components/tree/tree.scss
6926 这个规范需要重新寻找解决方案，ztree不可以添加overflow
https://github.com/rdkmaster/jigsaw/pull/2001
> [故障] 解决tree组件在添加overflow后，父容器无法正确显示滚动条的问题；关联@6926，@5316

- src/jigsaw/pc-components/box/box.html
- src/jigsaw/pc-components/box/box.scss
- src/jigsaw/pc-components/box/box.ts
- src/jigsaw/pc-components/box/editable-box.ts
Change-Id: If43040c415627b808e3a25caf6dfdea20ddde9ee
> [新增] 普通布局盒子支持渲染点，优化改变尺寸线条的位置算法,关联@5260

- src/jigsaw/pc-components/graph/graph.scss
- src/jigsaw/pc-components/graph/graph.ts
Change-Id: If7e8dce73442055880ae3a31193ae9ddf21bae06
> [优化] 图形组件可以自动监听父级尺寸的变化重新渲染，关联@5676

- src/jigsaw/pc-components/box/box.ts
- src/jigsaw/pc-components/box/editable-box.ts
Change-Id: I70b7dbf4273a8bc2985b67e5d0126d7ca592825d
> [故障] 解决了盒子的拖拽改变尺寸的线不随盒子销毁而销毁的问题，关联@5121

- src/jigsaw/common/core/theming/echarts-theme.ts
Change-Id: I6937198246a662da666128106d2480d49da7643b
> [故障] 修复亮色图形皮肤下，坐标轴线颜色太淡的问题，关联@5100

- src/app/for-internal/demo/pc/table/sortable/demo.component.html
- src/app/for-internal/demo/pc/table/sortable/demo.component.ts
- src/jigsaw/pc-components/table/table-inner.components.ts
其实本来就有这个API，但是没有触发变更检查，所以没有效果。
> [新增] 表格组件新增手动重置排序按钮方法，关联了@5074

- src/jigsaw/pc-components/upload/upload.ts
Change-Id: I39a30e6c3d4906677904d41a286ef9d27370dbda
> [故障] 修复获取上传文件的文件列表报错，关联@5066

- src/jigsaw/common/directive/menu/cascading-menu.ts
- src/jigsaw/common/service/popup.service.ts
- src/jigsaw/pc-components/graph/graph.ts
Change-Id: I750ea325ac6520aa46158ba4d8c8c8885ea17eeb
> [故障] 修复皮肤服务切换皮肤不彻底的问题，关联@5063,@5069,@5194

- src/jigsaw/pc-components/box/box.ts
- src/jigsaw/pc-components/box/common-box.ts
Change-Id: I6fe5644e9eaa452cfaa691c754d1fb3ad3b50895
> [故障] 修复box滚动时会产出原生滚动条，关联@5040

- src/app/for-external/demo/box/middle-resize-line/demo.component.css
- src/app/for-external/demo/box/middle-resize-line/demo.component.html
- src/app/for-internal/demo/pc/box/middle-resize-line/demo.component.css
- src/app/for-internal/demo/pc/box/middle-resize-line/demo.component.html
- src/jigsaw/pc-components/box/box.scss
- src/jigsaw/pc-components/box/box.ts
- src/jigsaw/pc-components/box/common-box.ts
- src/jigsaw/pc-components/box/editable-box.scss
- src/jigsaw/pc-components/box/editable-box.ts
Change-Id: Iefb41c06d14f32383c46642b4a162faba8125384
> [新增] box新增gap属性用于简化尺寸可调整模式的使用，调整尺寸的手柄支持皮肤，关联@5147

- src/jigsaw/common/core/theming/prebuilt/settings/idea-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-light.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-dark.scss
- src/jigsaw/common/core/theming/prebuilt/settings/vmax-pro-light.scss
Change-Id: Ic7e4030503eff9e7ca534762572ac2373ea8108f
> [新增] 增加--bg-app应用级默认背景色css变量，关联@4940

- src/jigsaw/pc-components/box/box.scss
> [优化] 扩大box拖动改变尺寸线的鼠标响应范围，解决了@5020

- src/jigsaw/common/core/theming/prebuilt/settings/paletx-pro-base.scss
增加/*@public*/使得awade能访问得到css变量
> [新增] 开放zindex-popover相关css变量，关联@4861

- src/jigsaw/common/core/data/modeled-graph-data.ts
修改点：
- 删除了无用的ModeledGraphTemplate
- 各图形配置属性采用extends扩展属性，而不是枚举属性添加
> [优化] 可视化图形的属性配置扩展，关联@4845

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: I78607439eaea94e9cc000e5372c07026ec958765
> [新增] 可视化仪表盘支持轴线颜色根据数据自动变化，关联@4845,@5194

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: Icf40979064d3c8225447f198d1e67f4d649383e0
> [优化] 可视化图形维度指标扩展，关联@4845

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: Icdf14bc4b2aac41d77a4b56c6762be32275e8fb3
> [优化] 可视化坐标图的数据中自动分配的维度值需要按照图形类型呈现数据，关联@4795

- src/jigsaw/pc-components/date-and-time/time-picker.ts
http://localhost:4200/#/pc/date-time-picker/date-time-select
> [新增] 时间选择器新增回车确认功能

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: Iddfcdc1b12df556bbd1a145d399d2c9639d476d3
> [优化] 雷达图在添加维度值，或者从数据里自动获取维度值时，根据原图生成是否填充背景，关联@4786

- src/app/for-internal/demo/pc/large-text/common/demo.component.html
- src/app/for-internal/demo/pc/large-text/common/demo.component.ts
- src/jigsaw/pc-components/large-text/large-text.html
- src/jigsaw/pc-components/large-text/large-text.ts
> [新增] 大字组件除主体文字外支持设置渐变色，关联@4769

- src/jigsaw/common/core/data/modeled-graph-data.ts
Change-Id: Icc31c6f005588a4b514f949843803a755f6e9892
> [新增] 散点图支持从数据中自动获取维度值时，继承原图的散点样式，关联@4784

- src/app/for-internal/demo/pc/theme/wings-theme/demo.component.html
- src/jigsaw/common/service/popup.service.ts
- src/jigsaw/pc-components/combo-select/combo-select.ts
- src/jigsaw/pc-components/date-and-time/date-time-select.html
- src/jigsaw/pc-components/date-and-time/range-date-time-select.html
- src/jigsaw/pc-components/date-and-time/time-picker.ts
- src/jigsaw/pc-components/date-and-time/time-pop.scss
- src/jigsaw/pc-components/select/collapse-and-group-select.html
- src/jigsaw/pc-components/select/select.html
- src/jigsaw/pc-components/select/select.scss
已验证组件
Demo 地址http://localhost:4200/#/pc/theme/wings-theme
> [优化] 解决部分组件设置theme后弹出区域无效果的问题，关联了@4621

- src/app/for-internal/demo/pc/table/no-data/demo.component.css
- src/app/for-internal/demo/pc/table/no-data/demo.component.html
- src/app/for-internal/demo/pc/table/no-data/demo.component.ts
- src/jigsaw/pc-components/table/table.html
- src/jigsaw/pc-components/table/table.scss
- src/jigsaw/pc-components/table/table.ts
> [故障] 解决无数据表格在高度较小时，图片显示不全的问题，解决了@4621

- src/app/for-internal/demo/pc/transfer/transfer-list/demo.component.html
- src/app/for-internal/demo/pc/transfer/transfer-list/demo.component.ts
- src/jigsaw/pc-components/transfer/renderer/transfer-list.html
- src/jigsaw/pc-components/transfer/renderer/transfer-renderer.ts
- src/jigsaw/pc-components/transfer/transfer-renderer.scss
- src/jigsaw/pc-components/transfer/transfer.ts
> [新增] 穿梭框已选项列表新增点击图标配置，关联@4991

- src/jigsaw/pc-components/list-and-tile/button-bar.ts
Change-Id: I4e4051275fff85369c6af3871a7f8ed035e9ebe3
> [新增] button-bar添加autoRemoveInvalidValue属性，用于配置是否过滤无用数据，关联@4503

- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I80482ca6daeecb590877d655b609cb0a7f4e1c99
> [故障] 表格下拉框渲染器无法添加placeholder，关联@4462

- src/jigsaw/pc-components/table/table-renderer.ts
> [故障] 表格开关渲染器添加数据保护，关联了@4460

- src/app/for-internal/demo/pc/table/draggable-table/demo.component.html
- src/app/for-internal/demo/pc/table/draggable-table/demo.component.ts
- src/jigsaw/pc-components/table/table-renderer.ts
Change-Id: I4a8741a8ca724334b17c54d8a994efa7d00f72f8
> [新增] 表格拖拽渲染器可自动触发表格垂直滚动条滚动，避免记录数较多时需要多次拖动的问题，关联@4296,@4442

- src/app/for-internal/demo/pc/box/hidden/demo.component.html
- src/app/for-internal/demo/pc/box/hidden/demo.component.ts
- src/jigsaw/pc-components/box/box.html
- src/jigsaw/pc-components/box/box.scss
- src/jigsaw/pc-components/box/box.ts
- src/jigsaw/pc-components/box/editable-box.html
- src/jigsaw/pc-components/box/editable-box.ts
Change-Id: I2622c52e1f6c59d070bd41aea64ab9fa262f15f3
> [优化] box组件的resizeLine尺寸计算优化，解决了@4247
